#!/bin/bash 
  
  compile_scripts() {
    if [ ! -d "$1" ]; then
        echo "Error: Directory $1 does not exist."
        return 1
    fi

    for script in "$1"/*.sh; do
        if [ -f "$script" ]; then
            shc -f "$script"
            echo "Compiled: $script"
        else
            echo "No Bash scripts found in $1."
            break
        fi
    done
}
