#!/bin/bash
echo 'Installing packages...'
sudo apt install -y Listing...
sudo apt install -y accountsservice
sudo apt install -y acl
sudo apt install -y adb
sudo apt install -y adduser
sudo apt install -y adwaita-icon-theme
sudo apt install -y aide-common
sudo apt install -y aide
sudo apt install -y alsa-topology-conf
sudo apt install -y alsa-ucm-conf
sudo apt install -y alsa-utils
sudo apt install -y amavisd-new
sudo apt install -y anacron
sudo apt install -y analog
sudo apt install -y android-libbase
sudo apt install -y android-libboringssl
sudo apt install -y android-libcutils
sudo apt install -y android-liblog
sudo apt install -y android-libsparse
sudo apt install -y android-libziparchive
sudo apt install -y android-sdk-platform-tools-common
sudo apt install -y antiword
sudo apt install -y apache2-bin
sudo apt install -y apache2-data
sudo apt install -y apache2-doc
sudo apt install -y apache2-utils
sudo apt install -y apache2
sudo apt install -y apg
sudo apt install -y apparmor
sudo apt install -y appstream
sudo apt install -y apt-clone
sudo apt install -y apt-config-icons-hidpi
sudo apt install -y apt-config-icons
sudo apt install -y apt-listchanges
sudo apt install -y apt-transport-https
sudo apt install -y apt-utils
sudo apt install -y apt
sudo apt install -y aptdaemon-data
sudo apt install -y aptdaemon
sudo apt install -y arduino-builder
sudo apt install -y arduino-core-avr
sudo apt install -y arduino-ctags
sudo apt install -y arduino
sudo apt install -y aspell-en
sudo apt install -y aspell
sudo apt install -y at-spi2-common
sudo apt install -y at-spi2-core
sudo apt install -y attr
sudo apt install -y audacity-data
sudo apt install -y audacity
sudo apt install -y auditd
sudo apt install -y autoconf
sudo apt install -y automake
sudo apt install -y autopoint
sudo apt install -y autotools-dev
sudo apt install -y avahi-autoipd
sudo apt install -y avahi-daemon
sudo apt install -y avahi-utils
sudo apt install -y avr-libc
sudo apt install -y avrdude
sudo apt install -y baobab
sudo apt install -y base-files
sudo apt install -y base-passwd
sudo apt install -y bash-completion
sudo apt install -y bash
sudo apt install -y bc
sudo apt install -y bind9-dnsutils
sudo apt install -y bind9-host
sudo apt install -y bind9-libs
sudo apt install -y bind9-utils
sudo apt install -y bind9
sudo apt install -y binfmt-support
sudo apt install -y binutils-avr
sudo apt install -y binutils-common
sudo apt install -y binutils-x86-64-linux-gnu
sudo apt install -y binutils
sudo apt install -y blt
sudo apt install -y bluez-obexd
sudo apt install -y bluez
sudo apt install -y bolt
sudo apt install -y branding-ubuntu
sudo apt install -y bridge-utils
sudo apt install -y bsdextrautils
sudo apt install -y bsdmainutils
sudo apt install -y bsdutils
sudo apt install -y bubblewrap
sudo apt install -y busybox-initramfs
sudo apt install -y busybox-static
sudo apt install -y byobu
sudo apt install -y byzanz
sudo apt install -y bzip2
sudo apt install -y ca-certificates-java
sudo apt install -y ca-certificates
sudo apt install -y calibre-bin
sudo apt install -y calibre
sudo apt install -y cargo-binutils
sudo apt install -y cargo-c
sudo apt install -y cargo-doc
sudo apt install -y cargo-lichking
sudo apt install -y cargo-lock
sudo apt install -y cargo-outdated
sudo apt install -y casacore-data-igrf
sudo apt install -y catdoc
sudo apt install -y catdvi
sudo apt install -y certbot
sudo apt install -y checksecurity
sudo apt install -y cmake-data
sudo apt install -y cmake
sudo apt install -y cnijfilter2
sudo apt install -y colord-data
sudo apt install -y colord
sudo apt install -y command-not-found
sudo apt install -y console-setup-linux
sudo apt install -y console-setup
sudo apt install -y containerd
sudo apt install -y coreutils
sudo apt install -y cpio
sudo apt install -y cpp-11
sudo apt install -y cpp-12
sudo apt install -y cpp
sudo apt install -y cracklib-runtime
sudo apt install -y cron-daemon-common
sudo apt install -y cron
sudo apt install -y cu
sudo apt install -y cups-browsed
sudo apt install -y cups-bsd
sudo apt install -y cups-client
sudo apt install -y cups-common
sudo apt install -y cups-core-drivers
sudo apt install -y cups-daemon
sudo apt install -y cups-filters-core-drivers
sudo apt install -y cups-filters
sudo apt install -y cups-ipp-utils
sudo apt install -y cups-pk-helper
sudo apt install -y cups-ppdc
sudo apt install -y cups-server-common
sudo apt install -y cups
sudo apt install -y curl
sudo apt install -y dash
sudo apt install -y dbus-bin
sudo apt install -y dbus-daemon
sudo apt install -y dbus-session-bus-common
sudo apt install -y dbus-system-bus-common
sudo apt install -y dbus-user-session
sudo apt install -y dbus-x11
sudo apt install -y dbus
sudo apt install -y dconf-cli
sudo apt install -y dconf-gsettings-backend
sudo apt install -y dconf-service
sudo apt install -y dde-qt5integration
sudo apt install -y debconf-i18n
sudo apt install -y debconf
sudo apt install -y debianutils
sudo apt install -y deepin-screen-recorder
sudo apt install -y default-jre-headless
sudo apt install -y default-jre
sudo apt install -y deja-dup
sudo apt install -y desktop-file-utils
sudo apt install -y dialog
sudo apt install -y dictionaries-common
sudo apt install -y diffutils
sudo apt install -y dirmngr
sudo apt install -y distro-info-data
sudo apt install -y distro-info
sudo apt install -y djvulibre-bin
sudo apt install -y dmidecode
sudo apt install -y dmsetup
sudo apt install -y dmz-cursor-theme
sudo apt install -y dns-root-data
sudo apt install -y dnsmasq-base
sudo apt install -y dnsutils
sudo apt install -y docbook-xml
sudo apt install -y docker-buildx-plugin
sudo apt install -y docker-compose-plugin
sudo apt install -y docker.io
sudo apt install -y docker
sudo apt install -y docutils-common
sudo apt install -y docx2txt
sudo apt install -y dosfstools
sudo apt install -y dpkg-dev
sudo apt install -y dpkg-repack
sudo apt install -y dpkg
sudo apt install -y duplicity
sudo apt install -y dvisvgm
sudo apt install -y e2fsck-static
sudo apt install -y e2fsprogs-l10n
sudo apt install -y e2fsprogs
sudo apt install -y ed
sudo apt install -y efibootmgr
sudo apt install -y eject
sudo apt install -y emacsen-common
sudo apt install -y enchant-2
sudo apt install -y eog
sudo apt install -y espeak-data
sudo apt install -y espeak-ng-data
sudo apt install -y espeak
sudo apt install -y evince-common
sudo apt install -y evince
sudo apt install -y evolution-data-server-common
sudo apt install -y evolution-data-server
sudo apt install -y extra-xdg-menus
sudo apt install -y fakeroot
sudo apt install -y fastboot
sudo apt install -y fdclone
sudo apt install -y fdisk
sudo apt install -y ffmpeg
sudo apt install -y figlet
sudo apt install -y file-roller
sudo apt install -y file
sudo apt install -y finalrd
sudo apt install -y findutils
sudo apt install -y firefox
sudo apt install -y firmware-sof-signed
sudo apt install -y fontconfig-config
sudo apt install -y fontconfig
sudo apt install -y fonts-beng-extra
sudo apt install -y fonts-beng
sudo apt install -y fonts-dejavu-core
sudo apt install -y fonts-dejavu-extra
sudo apt install -y fonts-deva-extra
sudo apt install -y fonts-deva
sudo apt install -y fonts-droid-fallback
sudo apt install -y fonts-freefont-ttf
sudo apt install -y fonts-gargi
sudo apt install -y fonts-glyphicons-halflings
sudo apt install -y fonts-gubbi
sudo apt install -y fonts-gujr-extra
sudo apt install -y fonts-gujr
sudo apt install -y fonts-guru-extra
sudo apt install -y fonts-guru
sudo apt install -y fonts-indic
sudo apt install -y fonts-kacst-one
sudo apt install -y fonts-kacst
sudo apt install -y fonts-kalapi
sudo apt install -y fonts-khmeros-core
sudo apt install -y fonts-knda
sudo apt install -y fonts-lao
sudo apt install -y fonts-lato
sudo apt install -y fonts-liberation2
sudo apt install -y fonts-liberation
sudo apt install -y fonts-lklug-sinhala
sudo apt install -y fonts-lmodern
sudo apt install -y fonts-lohit-beng-assamese
sudo apt install -y fonts-lohit-beng-bengali
sudo apt install -y fonts-lohit-deva
sudo apt install -y fonts-lohit-gujr
sudo apt install -y fonts-lohit-guru
sudo apt install -y fonts-lohit-knda
sudo apt install -y fonts-lohit-mlym
sudo apt install -y fonts-lohit-orya
sudo apt install -y fonts-lohit-taml-classical
sudo apt install -y fonts-lohit-taml
sudo apt install -y fonts-lohit-telu
sudo apt install -y fonts-mlym
sudo apt install -y fonts-nakula
sudo apt install -y fonts-navilu
sudo apt install -y fonts-noto-cjk
sudo apt install -y fonts-noto-color-emoji
sudo apt install -y fonts-noto-core
sudo apt install -y fonts-noto-hinted
sudo apt install -y fonts-noto-mono
sudo apt install -y fonts-noto-ui-core
sudo apt install -y fonts-open-sans
sudo apt install -y fonts-opensymbol
sudo apt install -y fonts-orya-extra
sudo apt install -y fonts-orya
sudo apt install -y fonts-pagul
sudo apt install -y fonts-roboto-hinted
sudo apt install -y fonts-roboto-unhinted
sudo apt install -y fonts-sahadeva
sudo apt install -y fonts-samyak-deva
sudo apt install -y fonts-samyak-gujr
sudo apt install -y fonts-samyak-mlym
sudo apt install -y fonts-samyak-taml
sudo apt install -y fonts-sarai
sudo apt install -y fonts-sil-abyssinica
sudo apt install -y fonts-sil-annapurna
sudo apt install -y fonts-sil-padauk
sudo apt install -y fonts-smc-anjalioldlipi
sudo apt install -y fonts-smc-chilanka
sudo apt install -y fonts-smc-dyuthi
sudo apt install -y fonts-smc-gayathri
sudo apt install -y fonts-smc-karumbi
sudo apt install -y fonts-smc-keraleeyam
sudo apt install -y fonts-smc-manjari
sudo apt install -y fonts-smc-meera
sudo apt install -y fonts-smc-rachana
sudo apt install -y fonts-smc-raghumalayalamsans
sudo apt install -y fonts-smc-suruma
sudo apt install -y fonts-smc-uroob
sudo apt install -y fonts-smc
sudo apt install -y fonts-taml
sudo apt install -y fonts-telu-extra
sudo apt install -y fonts-telu
sudo apt install -y fonts-teluguvijayam
sudo apt install -y fonts-texgyre-math
sudo apt install -y fonts-texgyre
sudo apt install -y fonts-thai-tlwg
sudo apt install -y fonts-tibetan-machine

sudo apt install -y fortune-mod
sudo apt install -y fortunes-min
sudo apt install -y fprintd
sudo apt install -y friendly-recovery
sudo apt install -y ftp
sudo apt install -y fuse2fs
sudo apt install -y fuse3
sudo apt install -y fwupd-signed
sudo apt install -y fwupd
sudo apt install -y g++-12
sudo apt install -y galera-4
sudo apt install -y gamemode-daemon
sudo apt install -y gamemode
sudo apt install -y gamin
sudo apt install -y gawk
sudo apt install -y gcc-11-base
sudo apt install -y gcc-11
sudo apt install -y gcc-12-base
sudo apt install -y gcc-12
sudo apt install -y gcc-13-base
sudo apt install -y gcc-13-base
sudo apt install -y gcc-avr
sudo apt install -y gcc
sudo apt install -y gcr
sudo apt install -y gdal-data
sudo apt install -y gdal-plugins
sudo apt install -y gdb
sudo apt install -y gdisk
sudo apt install -y gdm3
sudo apt install -y gedit-common
sudo apt install -y gedit
sudo apt install -y gem-doc
sudo apt install -y gem-extra
sudo apt install -y gem-plugin-assimp
sudo apt install -y gem-plugin-gmerlin
sudo apt install -y gem-plugin-lqt
sudo apt install -y gem-plugin-magick
sudo apt install -y gem-plugin-v4l2
sudo apt install -y gem
sudo apt install -y genisoimage
sudo apt install -y geoclue-2.0
sudo apt install -y geocode-glib-common
sudo apt install -y gettext-base
sudo apt install -y gettext
sudo apt install -y ghostscript-x
sudo apt install -y ghostscript
sudo apt install -y gir1.2-accountsservice-1.0
sudo apt install -y gir1.2-adw-1
sudo apt install -y gir1.2-atk-1.0
sudo apt install -y gir1.2-atspi-2.0
sudo apt install -y gir1.2-dbusmenu-glib-0.4
sudo apt install -y gir1.2-dee-1.0
sudo apt install -y gir1.2-freedesktop
sudo apt install -y gir1.2-gck-1
sudo apt install -y gir1.2-gcr-3
sudo apt install -y gir1.2-gdesktopenums-3.0
sudo apt install -y gir1.2-gdkpixbuf-2.0
sudo apt install -y gir1.2-gdm-1.0
sudo apt install -y gir1.2-geoclue-2.0
sudo apt install -y gir1.2-glib-2.0
sudo apt install -y gir1.2-gmenu-3.0
sudo apt install -y gir1.2-gnomeautoar-0.1
sudo apt install -y gir1.2-gnomebg-4.0
sudo apt install -y gir1.2-gnomebluetooth-3.0
sudo apt install -y gir1.2-gnomedesktop-3.0
sudo apt install -y gir1.2-gnomedesktop-4.0
sudo apt install -y gir1.2-goa-1.0
sudo apt install -y gir1.2-graphene-1.0
sudo apt install -y gir1.2-gstreamer-1.0
sudo apt install -y gir1.2-gtk-3.0
sudo apt install -y gir1.2-gtk-4.0
sudo apt install -y gir1.2-gtksource-4
sudo apt install -y gir1.2-gudev-1.0
sudo apt install -y gir1.2-gweather-4.0
sudo apt install -y gir1.2-handy-1
sudo apt install -y gir1.2-harfbuzz-0.0
sudo apt install -y gir1.2-ibus-1.0
sudo apt install -y gir1.2-javascriptcoregtk-4.1
sudo apt install -y gir1.2-json-1.0
sudo apt install -y gir1.2-keybinder-3.0
sudo apt install -y gir1.2-mutter-12
sudo apt install -y gir1.2-nm-1.0
sudo apt install -y gir1.2-nma4-1.0
sudo apt install -y gir1.2-notify-0.7
sudo apt install -y gir1.2-packagekitglib-1.0
sudo apt install -y gir1.2-pango-1.0
sudo apt install -y gir1.2-peas-1.0
sudo apt install -y gir1.2-polkit-1.0
sudo apt install -y gir1.2-rsvg-2.0
sudo apt install -y gir1.2-secret-1
sudo apt install -y gir1.2-soup-3.0
sudo apt install -y gir1.2-totem-1.0
sudo apt install -y gir1.2-totemplparser-1.0
sudo apt install -y gir1.2-udisks-2.0
sudo apt install -y gir1.2-unity-7.0
sudo apt install -y gir1.2-upowerglib-1.0
sudo apt install -y gir1.2-vte-2.91
sudo apt install -y gir1.2-webkit2-4.1
sudo apt install -y gir1.2-wnck-3.0
sudo apt install -y git-man
sudo apt install -y git
sudo apt install -y gjs
sudo apt install -y gkbd-capplet
sudo apt install -y glib-networking-common
sudo apt install -y glib-networking-services
sudo apt install -y glib-networking
sudo apt install -y glogg
sudo apt install -y gnome-accessibility-themes
sudo apt install -y gnome-bluetooth-3-common
sudo apt install -y gnome-bluetooth-sendto
sudo apt install -y gnome-calculator
sudo apt install -y gnome-calendar
sudo apt install -y gnome-characters
sudo apt install -y gnome-control-center-data
sudo apt install -y gnome-control-center-faces
sudo apt install -y gnome-control-center
sudo apt install -y gnome-desktop3-data
sudo apt install -y gnome-disk-utility
sudo apt install -y gnome-font-viewer
sudo apt install -y gnome-initial-setup
sudo apt install -y gnome-keyring-pkcs11
sudo apt install -y gnome-keyring
sudo apt install -y gnome-logs
sudo apt install -y gnome-menus
sudo apt install -y gnome-online-accounts
sudo apt install -y gnome-power-manager
sudo apt install -y gnome-remote-desktop
sudo apt install -y gnome-session-bin
sudo apt install -y gnome-session-canberra
sudo apt install -y gnome-session-common
sudo apt install -y gnome-settings-daemon-common
sudo apt install -y gnome-settings-daemon
sudo apt install -y gnome-shell-common
sudo apt install -y gnome-shell-extension-appindicator
sudo apt install -y gnome-shell-extension-desktop-icons-ng
sudo apt install -y gnome-shell-extension-ubuntu-dock
sudo apt install -y gnome-shell
sudo apt install -y gnome-software-common
sudo apt install -y gnome-software-plugin-snap
sudo apt install -y gnome-software
sudo apt install -y gnome-startup-applications
sudo apt install -y gnome-system-monitor
sudo apt install -y gnome-terminal-data
sudo apt install -y gnome-terminal
sudo apt install -y gnome-text-editor
sudo apt install -y gnome-themes-extra-data
sudo apt install -y gnome-themes-extra
sudo apt install -y gnome-user-docs
sudo apt install -y gnupg-agent
sudo apt install -y gnupg-l10n
sudo apt install -y gnupg-utils
sudo apt install -y gnupg
sudo apt install -y golang-1.20-doc
sudo apt install -y golang-1.20-go
sudo apt install -y golang-1.20-src
sudo apt install -y golang-1.20
sudo apt install -y golang-doc
sudo apt install -y golang-go
sudo apt install -y golang-src
sudo apt install -y golang
sudo apt install -y google-chrome-stable
sudo apt install -y gpart
sudo apt install -y gparted-common
sudo apt install -y gparted
sudo apt install -y gpg-agent
sudo apt install -y gpg-wks-client
sudo apt install -y gpg-wks-server
sudo apt install -y gpg
sudo apt install -y gpgconf
sudo apt install -y gpgsm
sudo apt install -y gpgv
sudo apt install -y graphviz
sudo apt install -y grep
sudo apt install -y grilo-plugins-0.3-base
sudo apt install -y groff-base
sudo apt install -y grub-common
sudo apt install -y grub-efi-amd64-bin
sudo apt install -y grub-efi-amd64-signed
sudo apt install -y grub-gfxpayload-lists
sudo apt install -y grub-pc-bin
sudo apt install -y grub-pc
sudo apt install -y grub2-common
sudo apt install -y gsasl-common
sudo apt install -y gsettings-desktop-schemas
sudo apt install -y gsettings-ubuntu-schemas
sudo apt install -y gsfonts
sudo apt install -y gstreamer1.0-alsa
sudo apt install -y gstreamer1.0-fdkaac
sudo apt install -y gstreamer1.0-gl
sudo apt install -y gstreamer1.0-gtk3
sudo apt install -y gstreamer1.0-libav
sudo apt install -y gstreamer1.0-packagekit
sudo apt install -y gstreamer1.0-pipewire
sudo apt install -y gstreamer1.0-plugins-bad
sudo apt install -y gstreamer1.0-plugins-base-apps
sudo apt install -y gstreamer1.0-plugins-base
sudo apt install -y gstreamer1.0-plugins-good
sudo apt install -y gstreamer1.0-tools
sudo apt install -y gstreamer1.0-x
sudo apt install -y gtk-update-icon-cache
sudo apt install -y gtk2-engines-murrine
sudo apt install -y gtk2-engines-pixbuf
sudo apt install -y guile-3.0-libs
sudo apt install -y gvfs-backends
sudo apt install -y gvfs-common
sudo apt install -y gvfs-daemons
sudo apt install -y gvfs-fuse
sudo apt install -y gvfs-libs
sudo apt install -y gvfs
sudo apt install -y gzip
sudo apt install -y hdparm
sudo apt install -y hicolor-icon-theme
sudo apt install -y hostname
sudo apt install -y humanity-icon-theme
sudo apt install -y hunspell-en-us
sudo apt install -y hyphen-en-us
sudo apt install -y i965-va-driver
sudo apt install -y ibus-data
sudo apt install -y ibus-gtk3
sudo apt install -y ibus-gtk4
sudo apt install -y ibus-gtk
sudo apt install -y ibus-table
sudo apt install -y ibus
sudo apt install -y ibverbs-providers
sudo apt install -y iio-sensor-proxy
sudo apt install -y im-config
sudo apt install -y imagemagick-6-common
sudo apt install -y imagemagick-6-doc
sudo apt install -y imagemagick-6.q16
sudo apt install -y imagemagick-6.q16hdri
sudo apt install -y imagemagick-common
sudo apt install -y imagemagick-doc
sudo apt install -y imagemagick
sudo apt install -y inetutils-telnet
sudo apt install -y info
sudo apt install -y init-system-helpers
sudo apt install -y init
sudo apt install -y initramfs-tools-bin
sudo apt install -y initramfs-tools-core
sudo apt install -y inputattach
sudo apt install -y install-info
sudo apt install -y intel-media-va-driver
sudo apt install -y intltool-debian
sudo apt install -y ipp-usb
sudo apt install -y iproute2
sudo apt install -y iptables
sudo apt install -y iputils-ping
sudo apt install -y iputils-tracepath
sudo apt install -y irqbalance
sudo apt install -y isa-support
sudo apt install -y isc-dhcp-client
sudo apt install -y isc-dhcp-common
sudo apt install -y isc-dhcp-server
sudo apt install -y iso-codes
sudo apt install -y isympy-common
sudo apt install -y isympy3
sudo apt install -y jackd2-firewire
sudo apt install -y jackd2
sudo apt install -y jackd
sudo apt install -y java-common
sudo apt install -y java-wrappers
sudo apt install -y javascript-common
sudo apt install -y jq
sudo apt install -y kbd
sudo apt install -y kded5
sudo apt install -y keditbookmarks
sudo apt install -y kerneloops
sudo apt install -y keyboard-configuration
sudo apt install -y kio
sudo apt install -y klibc-utils
sudo apt install -y kmod
sudo apt install -y kodi-bin
sudo apt install -y kodi-data
sudo apt install -y kodi-repository-kodi
sudo apt install -y kodi-visualization-spectrum
sudo apt install -y kodi
sudo apt install -y konsole-kpart
sudo apt install -y konsole
sudo apt install -y kpackagelauncherqml
sudo apt install -y kpackagetool5
sudo apt install -y krb5-locales
sudo apt install -y kwayland-data
sudo apt install -y kwayland-integration
sudo apt install -y language-pack-en-base
sudo apt install -y language-pack-en
sudo apt install -y language-pack-gnome-en-base
sudo apt install -y language-pack-gnome-en
sudo apt install -y language-selector-common
sudo apt install -y language-selector-gnome
sudo apt install -y laptop-detect
sudo apt install -y ldap-utils
sudo apt install -y less
sudo apt install -y liba52-0.7.4
sudo apt install -y libaa1
sudo apt install -y libaacs0
sudo apt install -y libabsl20220623
sudo apt install -y libabw-0.1-1
sudo apt install -y libaccountsservice0
sudo apt install -y libacl1
sudo apt install -y libadwaita-1-0
sudo apt install -y libaec0
sudo apt install -y libalgorithm-diff-perl
sudo apt install -y libalgorithm-diff-xs-perl
sudo apt install -y libalgorithm-merge-perl
sudo apt install -y libamtk-5-0
sudo apt install -y libamtk-5-common
sudo apt install -y libann0
sudo apt install -y libao-common
sudo apt install -y libao4
sudo apt install -y libaom3
sudo apt install -y libapache-pom-java
sudo apt install -y libapparmor1
sudo apt install -y libappstream4
sudo apt install -y libapr1
sudo apt install -y libaprutil1-dbd-sqlite3
sudo apt install -y libaprutil1-ldap
sudo apt install -y libaprutil1
sudo apt install -y libapt-pkg6.0
sudo apt install -y libarchive-zip-perl
sudo apt install -y libarchive13
sudo apt install -y libargon2-1
sudo apt install -y libaribb24-0
sudo apt install -y libarmadillo11
sudo apt install -y libarpack2
sudo apt install -y libasan6
sudo apt install -y libasan8
sudo apt install -y libasound2-data
sudo apt install -y libasound2
sudo apt install -y libaspell15
sudo apt install -y libass9
sudo apt install -y libassimp5
sudo apt install -y libassuan0
sudo apt install -y libastylej-jni
sudo apt install -y libasyncns0
sudo apt install -y libatasmart4
sudo apt install -y libatk-adaptor
sudo apt install -y libatk-bridge2.0-0
sudo apt install -y libatk-wrapper-java-jni
sudo apt install -y libatk-wrapper-java
sudo apt install -y libatk1.0-0
sudo apt install -y libatkmm-1.6-1v5
sudo apt install -y libatm1
sudo apt install -y libatomic1
sudo apt install -y libatopology2
sudo apt install -y libatspi2.0-0
sudo apt install -y libattr1
sudo apt install -y libaudio2
sudo apt install -y libaudit-common
sudo apt install -y libaudit1
sudo apt install -y libauparse0
sudo apt install -y libauthen-sasl-perl
sudo apt install -y libavahi-client3
sudo apt install -y libavahi-common-data
sudo apt install -y libavahi-common3
sudo apt install -y libavahi-core7
sudo apt install -y libavahi-glib1
sudo apt install -y libavc1394-0
sudo apt install -y libavcodec59
sudo apt install -y libavdevice59
sudo apt install -y libavfilter8
sudo apt install -y libavformat59
sudo apt install -y libavutil57
sudo apt install -y libayatana-appindicator3-1
sudo apt install -y libayatana-ido3-0.4-0
sudo apt install -y libayatana-indicator3-7
sudo apt install -y libb2-1
sudo apt install -y libbabeltrace1
sudo apt install -y libbasicobjects0
sudo apt install -y libbatik-java
sudo apt install -y libbcg729-0
sudo apt install -y libbcpg-java
sudo apt install -y libbcprov-java
sudo apt install -y libbdplus0
sudo apt install -y libberkeleydb-perl
sudo apt install -y libbinutils
sudo apt install -y libblas3
sudo apt install -y libblkid-dev
sudo apt install -y libblkid1
sudo apt install -y libblockdev-crypto2
sudo apt install -y libblockdev-fs2
sudo apt install -y libblockdev-loop2
sudo apt install -y libblockdev-mdraid2
sudo apt install -y libblockdev-part-err2
sudo apt install -y libblockdev-part2
sudo apt install -y libblockdev-swap2
sudo apt install -y libblockdev-utils2
sudo apt install -y libblockdev2
sudo apt install -y libblosc1
sudo apt install -y libbluetooth3
sudo apt install -y libbluray2
sudo apt install -y libboost-atomic1.74-dev
sudo apt install -y libboost-atomic1.74.0
sudo apt install -y libboost-chrono1.74-dev
sudo apt install -y libboost-chrono1.74.0
sudo apt install -y libboost-context1.74-dev
sudo apt install -y libboost-context1.74.0
sudo apt install -y libboost-date-time1.74-dev
sudo apt install -y libboost-date-time1.74.0
sudo apt install -y libboost-dev
sudo apt install -y libboost-filesystem1.74.0
sudo apt install -y libboost-iostreams1.74.0
sudo apt install -y libboost-locale1.74.0
sudo apt install -y libboost-nowide1.74-dev
sudo apt install -y libboost-nowide1.74.0
sudo apt install -y libboost-numpy1.74-dev
sudo apt install -y libboost-numpy1.74.0
sudo apt install -y libboost-program-options1.74.0
sudo apt install -y libboost-python1.74.0
sudo apt install -y libboost-regex1.74.0
sudo apt install -y libboost-serialization1.74-dev
sudo apt install -y libboost-serialization1.74.0
sudo apt install -y libboost-system1.74-dev
sudo apt install -y libboost-system1.74.0
sudo apt install -y libboost-thread1.74-dev
sudo apt install -y libboost-thread1.74.0
sudo apt install -y libboost1.74-dev
sudo apt install -y libboost1.74-tools-dev
sudo apt install -y libbpf1
sudo apt install -y libbrlapi0.8
sudo apt install -y libbrotli1
sudo apt install -y libbs2b0
sudo apt install -y libbsd0
sudo apt install -y libburn4
sudo apt install -y libbytesize-common
sudo apt install -y libbytesize1
sudo apt install -y libbz2-1.0
sudo apt install -y libc-ares2
sudo apt install -y libc-bin
sudo apt install -y libc-dev-bin
sudo apt install -y libc-devtools
sudo apt install -y libc6-dbg
sudo apt install -y libc6-dev
sudo apt install -y libc6
sudo apt install -y libc6
sudo apt install -y libcaca0
sudo apt install -y libcairo-gobject-perl
sudo apt install -y libcairo-gobject2
sudo apt install -y libcairo-perl
sudo apt install -y libcairo-script-interpreter2
sudo apt install -y libcairo2
sudo apt install -y libcairomm-1.0-1v5
sudo apt install -y libcamel-1.2-64
sudo apt install -y libcanberra-gtk3-0
sudo apt install -y libcanberra-gtk3-module
sudo apt install -y libcanberra-pulse
sudo apt install -y libcanberra0
sudo apt install -y libcap-ng0
sudo apt install -y libcap2-bin
sudo apt install -y libcap2
sudo apt install -y libcap2
sudo apt install -y libcbor0.8
sudo apt install -y libcc1-0
sudo apt install -y libcddb2
sudo apt install -y libcdio-cdda2
sudo apt install -y libcdio-paranoia2
sudo apt install -y libcdio19
sudo apt install -y libcdparanoia0
sudo apt install -y libcdr-0.1-1
sudo apt install -y libcdt5
sudo apt install -y libcec6
sudo apt install -y libcephfs2
sudo apt install -y libcfitsio10
sudo apt install -y libcgi-fast-perl
sudo apt install -y libcgi-pm-perl
sudo apt install -y libcgraph6
sudo apt install -y libchm1
sudo apt install -y libchromaprint1
sudo apt install -y libcjson1
sudo apt install -y libclone-perl
sudo apt install -y libclucene-contribs1v5
sudo apt install -y libclucene-core1v5
sudo apt install -y libcodec2-1.0
sudo apt install -y libcolamd2
sudo apt install -y libcollection4
sudo apt install -y libcolord-gtk4-1
sudo apt install -y libcolord2
sudo apt install -y libcolorhug2
sudo apt install -y libcom-err2
sudo apt install -y libcom-err2
sudo apt install -y libcommon-sense-perl
sudo apt install -y libcommons-codec-java
sudo apt install -y libcommons-compress-java
sudo apt install -y libcommons-exec-java
sudo apt install -y libcommons-io-java
sudo apt install -y libcommons-lang3-java
sudo apt install -y libcommons-logging-java
sudo apt install -y libcommons-net-java
sudo apt install -y libcommons-parent-java
sudo apt install -y libconfig++9v5
sudo apt install -y libconfig-inifiles-perl
sudo apt install -y libconvert-binhex-perl
sudo apt install -y libconvert-tnef-perl
sudo apt install -y libconvert-uulib-perl
sudo apt install -y libcrack2
sudo apt install -y libcrossguid0
sudo apt install -y libcrypt-dev
sudo apt install -y libcrypt-openssl-bignum-perl
sudo apt install -y libcrypt-openssl-random-perl
sudo apt install -y libcrypt-openssl-rsa-perl
sudo apt install -y libcrypt1
sudo apt install -y libcrypt1
sudo apt install -y libcryptsetup12
sudo apt install -y libctf-nobfd0
sudo apt install -y libctf0
sudo apt install -y libcue2
sudo apt install -y libcups2
sudo apt install -y libcupsfilters2-common
sudo apt install -y libcupsfilters2
sudo apt install -y libcupsimage2
sudo apt install -y libcurl3-gnutls
sudo apt install -y libcurl4
sudo apt install -y libdaemon0
sudo apt install -y libdata-dump-perl
sudo apt install -y libdata-hexdump-perl
sudo apt install -y libdate-tz3
sudo apt install -y libdatrie1
sudo apt install -y libdav1d6
sudo apt install -y libdaxctl1
sudo apt install -y libdb5.3
sudo apt install -y libdbd-mysql-perl
sudo apt install -y libdbi-perl
sudo apt install -y libdbus-1-3
sudo apt install -y libdbus-1-3
sudo apt install -y libdbus-glib-1-2
sudo apt install -y libdbusmenu-glib4
sudo apt install -y libdbusmenu-gtk3-4
sudo apt install -y libdbusmenu-qt5-2
sudo apt install -y libdc1394-25
sudo apt install -y libdca0
sudo apt install -y libdconf1
sudo apt install -y libde265-0
sudo apt install -y libdebconfclient0
sudo apt install -y libdebuginfod-common
sudo apt install -y libdebuginfod1
sudo apt install -y libdecor-0-0
sudo apt install -y libdecor-0-plugin-1-cairo
sudo apt install -y libdee-1.0-4
sudo apt install -y libdeflate0
sudo apt install -y libdevmapper1.02.1
sudo apt install -y libdframeworkdbus2
sudo apt install -y libdhash1
sudo apt install -y libdigest-bubblebabble-perl
sudo apt install -y libdigest-hmac-perl
sudo apt install -y libdirectfb-1.7-7
sudo apt install -y libdjvulibre-text
sudo apt install -y libdjvulibre21
sudo apt install -y libdotconf0
sudo apt install -y libdouble-conversion3
sudo apt install -y libdpkg-perl
sudo apt install -y libdraco7
sudo apt install -y libdrm-amdgpu1
sudo apt install -y libdrm-common
sudo apt install -y libdrm-intel1
sudo apt install -y libdrm-nouveau2
sudo apt install -y libdrm-radeon1
sudo apt install -y libdrm2
sudo apt install -y libdtkcommon
sudo apt install -y libdtkcore5
sudo apt install -y libdtkgui5
sudo apt install -y libdtkwidget5
sudo apt install -y libdv4
sudo apt install -y libdvbpsi10
sudo apt install -y libdvdnav4
sudo apt install -y libdvdread8
sudo apt install -y libdw1
sudo apt install -y libe-book-0.1-1
sudo apt install -y libebackend-1.2-11
sudo apt install -y libebml5
sudo apt install -y libebook-1.2-21
sudo apt install -y libebook-contacts-1.2-4
sudo apt install -y libecal-2.0-2
sudo apt install -y libedata-book-1.2-27
sudo apt install -y libedata-cal-2.0-2
sudo apt install -y libedataserver-1.2-27
sudo apt install -y libedataserverui-1.2-4
sudo apt install -y libedataserverui4-1.0-0
sudo apt install -y libedit2
sudo apt install -y libeditorconfig0
sudo apt install -y libefiboot1
sudo apt install -y libefivar1
sudo apt install -y libegl-mesa0
sudo apt install -y libegl1
sudo apt install -y libelf1
sudo apt install -y libenca0
sudo apt install -y libenchant-2-2
sudo apt install -y libencode-locale-perl
sudo apt install -y libeot0
sudo apt install -y libepoxy0
sudo apt install -y libept1.6.0
sudo apt install -y libepubgen-0.1-1
sudo apt install -y liberror-perl
sudo apt install -y libespeak-ng1
sudo apt install -y libespeak1
sudo apt install -y libestr0
sudo apt install -y libetonyek-0.1-1
sudo apt install -y libevdev2
sudo apt install -y libevdocument3-4
sudo apt install -y libevent-2.1-7
sudo apt install -y libevent-2.1-7a
sudo apt install -y libevent-core-2.1-7
sudo apt install -y libevent-core-2.1-7a
sudo apt install -y libevview3-3
sudo apt install -y libexempi8
sudo apt install -y libexif12
sudo apt install -y libexiv2-27
sudo apt install -y libexpat1-dev
sudo apt install -y libexpat1
sudo apt install -y libext2fs2
sudo apt install -y libexttextcat-2.0-0
sudo apt install -y libexttextcat-data
sudo apt install -y libextutils-depends-perl
sudo apt install -y libfaad2
sudo apt install -y libfakeroot
sudo apt install -y libfastjson4
sudo apt install -y libfcgi-bin
sudo apt install -y libfcgi-perl
sudo apt install -y libfcgi0ldbl
sudo apt install -y libfdisk1
sudo apt install -y libfdk-aac2
sudo apt install -y libffado2
sudo apt install -y libffi-dev
sudo apt install -y libffi8
sudo apt install -y libfftw3-double3
sudo apt install -y libfftw3-single3
sudo apt install -y libfido2-1
sudo apt install -y libfile-basedir-perl
sudo apt install -y libfile-desktopentry-perl
sudo apt install -y libfile-fcntllock-perl
sudo apt install -y libfile-mimeinfo-perl
sudo apt install -y libflac++10
sudo apt install -y libflac12
sudo apt install -y libflashrom1
sudo apt install -y libflite1
sudo apt install -y libfltk1.3
sudo apt install -y libfluidsynth3
sudo apt install -y libfmt9
sudo apt install -y libfontconfig1
sudo apt install -y libfontenc1
sudo apt install -y libfprint-2-2
sudo apt install -y libfprint-2-tod1
sudo apt install -y libfreeaptx0
sudo apt install -y libfreehand-0.1-1
sudo apt install -y libfreerdp-server2-2
sudo apt install -y libfreerdp2-2
sudo apt install -y libfreetype6
sudo apt install -y libfreexl1
sudo apt install -y libfribidi0
sudo apt install -y libfstrcmp0
sudo apt install -y libftdi1-2
sudo apt install -y libftdi1
sudo apt install -y libftgl2
sudo apt install -y libfuse2
sudo apt install -y libfuse3-3
sudo apt install -y libfwupd2
sudo apt install -y libfyba0
sudo apt install -y libgail-common
sudo apt install -y libgail18
sudo apt install -y libgamemode0
sudo apt install -y libgamemode0
sudo apt install -y libgamemodeauto0
sudo apt install -y libgamemodeauto0
sudo apt install -y libgamin0
sudo apt install -y libgavl2
sudo apt install -y libgbm1
sudo apt install -y libgc1
sudo apt install -y libgcab-1.0-0
sudo apt install -y libgcc-11-dev
sudo apt install -y libgcc-12-dev
sudo apt install -y libgcc-s1
sudo apt install -y libgcc-s1
sudo apt install -y libgck-1-0
sudo apt install -y libgcr-base-3-1
sudo apt install -y libgcr-ui-3-1
sudo apt install -y libgcrypt20
sudo apt install -y libgcrypt20
sudo apt install -y libgd3
sudo apt install -y libgdal32
sudo apt install -y libgdata-common
sudo apt install -y libgdata22
sudo apt install -y libgdbm-compat4
sudo apt install -y libgdbm6
sudo apt install -y libgdk-pixbuf-2.0-0
sudo apt install -y libgdk-pixbuf2.0-bin
sudo apt install -y libgdk-pixbuf2.0-common
sudo apt install -y libgdm1
sudo apt install -y libgee-0.8-2
sudo apt install -y libgeoclue-2-0
sudo apt install -y libgeocode-glib-2-0
sudo apt install -y libgeos-c1v5
sudo apt install -y libgeos3.11.1
sudo apt install -y libgeotiff5
sudo apt install -y libgexiv2-2
sudo apt install -y libgfapi0
sudo apt install -y libgfortran5
sudo apt install -y libgfrpc0
sudo apt install -y libgfxdr0
sudo apt install -y libgif7
sudo apt install -y libgirepository-1.0-1
sudo apt install -y libgit2-1.5
sudo apt install -y libgjs0g
sudo apt install -y libgl1-amber-dri
sudo apt install -y libgl1-mesa-dri
sudo apt install -y libgl1
sudo apt install -y libglapi-mesa
sudo apt install -y libgles2
sudo apt install -y libglib-object-introspection-perl
sudo apt install -y libglib-perl
sudo apt install -y libglib2.0-0
sudo apt install -y libglib2.0-bin
sudo apt install -y libglib2.0-data
sudo apt install -y libglib2.0-dev-bin
sudo apt install -y libglib2.0-dev
sudo apt install -y libglibmm-2.4-1v5
sudo apt install -y libglu1-mesa
sudo apt install -y libglusterfs0
sudo apt install -y libglvnd0
sudo apt install -y libglx-mesa0
sudo apt install -y libglx0
sudo apt install -y libgme0
sudo apt install -y libgmerlin-avdec2
sudo apt install -y libgmime-3.0-0
sudo apt install -y libgmp10
sudo apt install -y libgnome-autoar-0-0
sudo apt install -y libgnome-bg-4-2
sudo apt install -y libgnome-bluetooth-3.0-13
sudo apt install -y libgnome-bluetooth-ui-3.0-13
sudo apt install -y libgnome-desktop-3-20
sudo apt install -y libgnome-desktop-4-2
sudo apt install -y libgnome-menu-3-0
sudo apt install -y libgnome-rr-4-2
sudo apt install -y libgnomekbd-common
sudo apt install -y libgnomekbd8
sudo apt install -y libgnutls30
sudo apt install -y libgoa-1.0-0b
sudo apt install -y libgoa-1.0-common
sudo apt install -y libgoa-backend-1.0-1
sudo apt install -y libgom-1.0-0
sudo apt install -y libgomp1
sudo apt install -y libgoogle-gson-java
sudo apt install -y libgpg-error-l10n
sudo apt install -y libgpg-error0
sudo apt install -y libgpg-error0
sudo apt install -y libgpgme11
sudo apt install -y libgpgmepp6
sudo apt install -y libgphoto2-6
sudo apt install -y libgphoto2-l10n
sudo apt install -y libgphoto2-port12
sudo apt install -y libgpm2
sudo apt install -y libgprofng0
sudo apt install -y libgraphene-1.0-0
sudo apt install -y libgraphicsmagick++-q16-12
sudo apt install -y libgraphicsmagick-q16-3
sudo apt install -y libgraphite2-3
sudo apt install -y libgrilo-0.3-0
sudo apt install -y libgs-common
sudo apt install -y libgs10-common
sudo apt install -y libgs10
sudo apt install -y libgsasl18
sudo apt install -y libgsettings-qt1
sudo apt install -y libgsf-1-114
sudo apt install -y libgsf-1-common
sudo apt install -y libgsm1
sudo apt install -y libgsound0
sudo apt install -y libgspell-1-2
sudo apt install -y libgspell-1-common
sudo apt install -y libgssapi-krb5-2
sudo apt install -y libgssapi-krb5-2
sudo apt install -y libgssdp-1.6-0
sudo apt install -y libgstreamer-gl1.0-0
sudo apt install -y libgstreamer-plugins-bad1.0-0
sudo apt install -y libgstreamer-plugins-base1.0-0
sudo apt install -y libgstreamer-plugins-good1.0-0
sudo apt install -y libgstreamer1.0-0
sudo apt install -y libgtk-3-0
sudo apt install -y libgtk-3-bin
sudo apt install -y libgtk-3-common
sudo apt install -y libgtk-4-1
sudo apt install -y libgtk-4-bin
sudo apt install -y libgtk-4-common
sudo apt install -y libgtk-4-media-gstreamer
sudo apt install -y libgtk2.0-0
sudo apt install -y libgtk2.0-bin
sudo apt install -y libgtk2.0-common
sudo apt install -y libgtk3-perl
sudo apt install -y libgtkmm-3.0-1v5
sudo apt install -y libgtksourceview-4-0
sudo apt install -y libgtksourceview-4-common
sudo apt install -y libgtksourceview-5-0
sudo apt install -y libgtksourceview-5-common
sudo apt install -y libgtop-2.0-11
sudo apt install -y libgtop2-common
sudo apt install -y libgts-0.7-5
sudo apt install -y libgts-bin
sudo apt install -y libgudev-1.0-0
sudo apt install -y libgumbo1
sudo apt install -y libgupnp-1.6-0
sudo apt install -y libgupnp-av-1.0-3
sudo apt install -y libgupnp-dlna-2.0-4
sudo apt install -y libgupnp-igd-1.0-4
sudo apt install -y libgusb2
sudo apt install -y libgvc6
sudo apt install -y libgvpr2
sudo apt install -y libgweather-4-0
sudo apt install -y libgweather-4-common
sudo apt install -y libgxps2
sudo apt install -y libhandy-1-0
sudo apt install -y libharfbuzz-icu0
sudo apt install -y libharfbuzz-subset0
sudo apt install -y libharfbuzz0b
sudo apt install -y libhdf4-0-alt
sudo apt install -y libhdf5-103-1
sudo apt install -y libhdf5-hl-100
sudo apt install -y libheif1
sudo apt install -y libhfstospell11
sudo apt install -y libhidapi-libusb0
sudo apt install -y libhiredis0.14
sudo apt install -y libhogweed6
sudo apt install -y libhtml-parser-perl
sudo apt install -y libhtml-tagset-perl
sudo apt install -y libhtml-template-perl
sudo apt install -y libhttp-date-perl
sudo apt install -y libhttp-message-perl
sudo apt install -y libhttp-parser2.9
sudo apt install -y libhttpclient-java
sudo apt install -y libhttpcore-java
sudo apt install -y libhunspell-1.7-0
sudo apt install -y libhwy1
sudo apt install -y libhyphen0
sudo apt install -y libibus-1.0-5
sudo apt install -y libibverbs1
sudo apt install -y libical3
sudo apt install -y libice6
sudo apt install -y libicu72
sudo apt install -y libid3tag0
sudo apt install -y libidn12
sudo apt install -y libidn2-0
sudo apt install -y libidn2-0
sudo apt install -y libiec61883-0
sudo apt install -y libieee1284-3
sudo apt install -y libigdgmm12
sudo apt install -y libijs-0.35
sudo apt install -y libimagequant0
sudo apt install -y libimath-3-1-29
sudo apt install -y libimobiledevice6
sudo apt install -y libini-config5
sudo apt install -y libinih1
sudo apt install -y libinput-bin
sudo apt install -y libinput10
sudo apt install -y libinstpatch-1.0-2
sudo apt install -y libio-html-perl
sudo apt install -y libio-multiplex-perl
sudo apt install -y libio-socket-inet6-perl
sudo apt install -y libio-socket-ssl-perl
sudo apt install -y libio-stringy-perl
sudo apt install -y libip4tc2
sudo apt install -y libip6tc2
sudo apt install -y libipa-hbac0
sudo apt install -y libipc-signal-perl
sudo apt install -y libipc-system-simple-perl
sudo apt install -y libipt2
sudo apt install -y libisl23
sudo apt install -y libiso9660-11
sudo apt install -y libisoburn1
sudo apt install -y libisofs6
sudo apt install -y libitm1
sudo apt install -y libiw30
sudo apt install -y libixml10
sudo apt install -y libjack-jackd2-0
sudo apt install -y libjackson2-annotations-java
sudo apt install -y libjackson2-core-java
sudo apt install -y libjackson2-databind-java
sudo apt install -y libjansson4
sudo apt install -y libjavascriptcoregtk-4.1-0
sudo apt install -y libjavascriptcoregtk-6.0-1
sudo apt install -y libjaxp1.3-java
sudo apt install -y libjbig0
sudo apt install -y libjbig2dec0
sudo apt install -y libjcat1
sudo apt install -y libjmdns-java
sudo apt install -y libjna-java
sudo apt install -y libjna-jni
sudo apt install -y libjna-platform-java
sudo apt install -y libjpeg-turbo-progs
sudo apt install -y libjpeg-turbo8
sudo apt install -y libjpeg8
sudo apt install -y libjq1
sudo apt install -y libjs-bootstrap
sudo apt install -y libjs-iscroll
sudo apt install -y libjs-jquery-easing
sudo apt install -y libjs-jquery-fancybox
sudo apt install -y libjs-jquery-mousewheel
sudo apt install -y libjs-jquery
sudo apt install -y libjs-sphinxdoc
sudo apt install -y libjs-underscore
sudo apt install -y libjsch-java
sudo apt install -y libjson-c5
sudo apt install -y libjson-glib-1.0-0
sudo apt install -y libjson-glib-1.0-common
sudo apt install -y libjson-perl
sudo apt install -y libjson-xs-perl
sudo apt install -y libjsoncpp25
sudo apt install -y libjssc-java
sudo apt install -y libjxl0.7
sudo apt install -y libjxr-tools
sudo apt install -y libjxr0
sudo apt install -y libjzlib-java
sudo apt install -y libk5crypto3
sudo apt install -y libk5crypto3
sudo apt install -y libkate1
sudo apt install -y libkeybinder-3.0-0
sudo apt install -y libkeyutils1
sudo apt install -y libkeyutils1
sudo apt install -y libkf5archive-data
sudo apt install -y libkf5archive5
sudo apt install -y libkf5attica5
sudo apt install -y libkf5auth-data
sudo apt install -y libkf5authcore5
sudo apt install -y libkf5bookmarks-data
sudo apt install -y libkf5bookmarks5
sudo apt install -y libkf5codecs-data
sudo apt install -y libkf5codecs5
sudo apt install -y libkf5completion-data
sudo apt install -y libkf5completion5
sudo apt install -y libkf5config-bin
sudo apt install -y libkf5config-data
sudo apt install -y libkf5configcore5
sudo apt install -y libkf5configgui5
sudo apt install -y libkf5configwidgets-data
sudo apt install -y libkf5configwidgets5
sudo apt install -y libkf5coreaddons-data
sudo apt install -y libkf5coreaddons5
sudo apt install -y libkf5crash5
sudo apt install -y libkf5dbusaddons-bin
sudo apt install -y libkf5dbusaddons-data
sudo apt install -y libkf5dbusaddons5
sudo apt install -y libkf5declarative-data
sudo apt install -y libkf5declarative5
sudo apt install -y libkf5doctools5
sudo apt install -y libkf5globalaccel-bin
sudo apt install -y libkf5globalaccel-data
sudo apt install -y libkf5globalaccel5
sudo apt install -y libkf5globalaccelprivate5
sudo apt install -y libkf5guiaddons-bin
sudo apt install -y libkf5guiaddons-data
sudo apt install -y libkf5guiaddons5
sudo apt install -y libkf5i18n-data
sudo apt install -y libkf5i18n5
sudo apt install -y libkf5iconthemes-bin
sudo apt install -y libkf5iconthemes-data
sudo apt install -y libkf5iconthemes5
sudo apt install -y libkf5itemviews-data
sudo apt install -y libkf5itemviews5
sudo apt install -y libkf5jobwidgets-data
sudo apt install -y libkf5jobwidgets5
sudo apt install -y libkf5kiocore5
sudo apt install -y libkf5kiogui5
sudo apt install -y libkf5kiontlm5
sudo apt install -y libkf5kiowidgets5
sudo apt install -y libkf5kirigami2-5
sudo apt install -y libkf5newstuff-data
sudo apt install -y libkf5newstuff5
sudo apt install -y libkf5newstuffcore5
sudo apt install -y libkf5newstuffwidgets5
sudo apt install -y libkf5notifications-data
sudo apt install -y libkf5notifications5
sudo apt install -y libkf5notifyconfig-data
sudo apt install -y libkf5notifyconfig5
sudo apt install -y libkf5package-data
sudo apt install -y libkf5package5
sudo apt install -y libkf5parts-data
sudo apt install -y libkf5parts-plugins
sudo apt install -y libkf5parts5
sudo apt install -y libkf5pty-data
sudo apt install -y libkf5pty5
sudo apt install -y libkf5quickaddons5
sudo apt install -y libkf5service-bin
sudo apt install -y libkf5service-data
sudo apt install -y libkf5service5
sudo apt install -y libkf5solid5-data
sudo apt install -y libkf5solid5
sudo apt install -y libkf5sonnet5-data
sudo apt install -y libkf5sonnetcore5
sudo apt install -y libkf5sonnetui5
sudo apt install -y libkf5syndication5abi1
sudo apt install -y libkf5textwidgets-data
sudo apt install -y libkf5textwidgets5
sudo apt install -y libkf5wallet-bin
sudo apt install -y libkf5wallet-data
sudo apt install -y libkf5wallet5
sudo apt install -y libkf5waylandclient5
sudo apt install -y libkf5widgetsaddons-data
sudo apt install -y libkf5widgetsaddons5
sudo apt install -y libkf5windowsystem-data
sudo apt install -y libkf5windowsystem5
sudo apt install -y libkf5xmlgui-bin
sudo apt install -y libkf5xmlgui-data
sudo apt install -y libkf5xmlgui5
sudo apt install -y libkissfft-float131
sudo apt install -y libklibc
sudo apt install -y libkmlbase1
sudo apt install -y libkmldom1
sudo apt install -y libkmlengine1
sudo apt install -y libkmod2
sudo apt install -y libkpathsea6
sudo apt install -y libkrb5-3
sudo apt install -y libkrb5-3
sudo apt install -y libkrb5support0
sudo apt install -y libkrb5support0
sudo apt install -y libksba8
sudo apt install -y libkwalletbackend5-5
sudo apt install -y liblab-gamut1
sudo apt install -y liblangtag-common
sudo apt install -y liblangtag1
sudo apt install -y liblapack3
sudo apt install -y liblbfgsb0
sudo apt install -y liblc3-0
sudo apt install -y liblcms2-2
sudo apt install -y liblcms2-utils
sudo apt install -y libldacbt-abr2
sudo apt install -y libldacbt-enc2
sudo apt install -y libldap-common
sudo apt install -y libldap2
sudo apt install -y libldb2
sudo apt install -y liblerc4
sudo apt install -y liblightcouch-java
sudo apt install -y liblilv-0-0
sudo apt install -y liblinear4
sudo apt install -y liblirc-client0
sudo apt install -y liblistserialsj-dev
sudo apt install -y liblistserialsj1
sudo apt install -y libllvm15
sudo apt install -y liblmdb0
sudo apt install -y liblocale-gettext-perl
sudo apt install -y liblockfile-bin
sudo apt install -y liblockfile1
sudo apt install -y liblog4j2-java
sudo apt install -y liblouis-bin
sudo apt install -y liblouis-data
sudo apt install -y liblouis20
sudo apt install -y liblqr-1-0
sudo apt install -y liblrdf0
sudo apt install -y liblsan0
sudo apt install -y libltc11
sudo apt install -y libltdl7
sudo apt install -y liblua5.2-0
sudo apt install -y liblua5.3-0
sudo apt install -y liblwp-mediatypes-perl
sudo apt install -y liblz4-1
sudo apt install -y liblz4-1
sudo apt install -y liblzma5
sudo apt install -y liblzma5
sudo apt install -y liblzo2-2
sudo apt install -y libmad0
sudo apt install -y libmagic-mgc
sudo apt install -y libmagic1
sudo apt install -y libmagick++-6.q16-8
sudo apt install -y libmagickcore-6.q16-6-extra
sudo apt install -y libmagickcore-6.q16-6
sudo apt install -y libmagickcore-6.q16hdri-6-extra
sudo apt install -y libmagickcore-6.q16hdri-6
sudo apt install -y libmagickwand-6.q16-6
sudo apt install -y libmagickwand-6.q16hdri-6
sudo apt install -y libmail-authenticationresults-perl
sudo apt install -y libmail-dkim-perl
sudo apt install -y libmail-sendmail-perl
sudo apt install -y libmailtools-perl
sudo apt install -y libmailutils9
sudo apt install -y libmalcontent-0-0
sudo apt install -y libmanette-0.2-0
sudo apt install -y libmapcache1
sudo apt install -y libmariadb3
sudo apt install -y libmatroska7
sudo apt install -y libmaxminddb0
sudo apt install -y libmbedcrypto7
sudo apt install -y libmbim-glib4
sudo apt install -y libmbim-proxy
sudo apt install -y libmbim-utils
sudo apt install -y libmd0
sudo apt install -y libmd4c0
sudo apt install -y libmediaart-2.0-0
sudo apt install -y libmfx1
sudo apt install -y libmhash2
sudo apt install -y libmicrohttpd12
sudo apt install -y libmime-tools-perl
sudo apt install -y libmime-types-perl
sudo apt install -y libminiupnpc17
sudo apt install -y libminizip1
sudo apt install -y libmjpegutils-2.1-0
sudo apt install -y libmm-glib0
sudo apt install -y libmng2
sudo apt install -y libmnl0
sudo apt install -y libmodplug1
sudo apt install -y libmongodb-java
sudo apt install -y libmount-dev
sudo apt install -y libmount1
sudo apt install -y libmozjs-102-0
sudo apt install -y libmp3lame0
sudo apt install -y libmpc3
sudo apt install -y libmpcdec6
sudo apt install -y libmpeg2-4
sudo apt install -y libmpeg2encpp-2.1-0
sudo apt install -y libmpfr6
sudo apt install -y libmpg123-0
sudo apt install -y libmplex2-2.1-0
sudo apt install -y libmspub-0.1-1
sudo apt install -y libmtdev1
sudo apt install -y libmtp-common
sudo apt install -y libmtp-runtime
sudo apt install -y libmtp9
sudo apt install -y libmujs2
sudo apt install -y libmutter-12-0
sudo apt install -y libmwaw-0.3-3
sudo apt install -y libmysofa1
sudo apt install -y libmysqlclient21
sudo apt install -y libmythes-1.2-0
sudo apt install -y libnatpmp1
sudo apt install -y libnautilus-extension4
sudo apt install -y libncurses6
sudo apt install -y libncursesw6
sudo apt install -y libndctl6
sudo apt install -y libndp0
sudo apt install -y libneon27
sudo apt install -y libnet-cidr-lite-perl
sudo apt install -y libnet-cidr-perl
sudo apt install -y libnet-dns-perl
sudo apt install -y libnet-dns-sec-perl
sudo apt install -y libnet-libidn-perl
sudo apt install -y libnet-patricia-perl
sudo apt install -y libnet-server-perl
sudo apt install -y libnet-smtp-ssl-perl
sudo apt install -y libnet-snmp-perl
sudo apt install -y libnet-ssleay-perl
sudo apt install -y libnetcdf19
sudo apt install -y libnetfilter-conntrack3
sudo apt install -y libnetpbm11
sudo apt install -y libnetplan0
sudo apt install -y libnettle8
sudo apt install -y libnewt0.52
sudo apt install -y libnfnetlink0
sudo apt install -y libnfs13
sudo apt install -y libnfsidmap1
sudo apt install -y libnftables1
sudo apt install -y libnftnl11
sudo apt install -y libnghttp2-14
sudo apt install -y libnice10
sudo apt install -y libnl-3-200
sudo apt install -y libnl-genl-3-200
sudo apt install -y libnl-route-3-200
sudo apt install -y libnm0
sudo apt install -y libnma-common
sudo apt install -y libnma-gtk4-0
sudo apt install -y libnma0
sudo apt install -y libnorm1
sudo apt install -y libnotify-bin
sudo apt install -y libnotify4
sudo apt install -y libnpth0
sudo apt install -y libnsl-dev
sudo apt install -y libnsl2
sudo apt install -y libnsl2
sudo apt install -y libnspr4
sudo apt install -y libnss-mdns
sudo apt install -y libnss-nis
sudo apt install -y libnss-nis
sudo apt install -y libnss-nisplus
sudo apt install -y libnss-nisplus
sudo apt install -y libnss-sss
sudo apt install -y libnss-systemd
sudo apt install -y libnss3
sudo apt install -y libntfs-3g89
sudo apt install -y libntlm0
sudo apt install -y libnuma1
sudo apt install -y libodbc2
sudo apt install -y libodbcinst2
sudo apt install -y libodfgen-0.1-1
sudo apt install -y libogdi4.1
sudo apt install -y libogg0
sudo apt install -y libonig5
sudo apt install -y libopenal-data
sudo apt install -y libopenal1
sudo apt install -y libopenblas-dev
sudo apt install -y libopenblas-pthread-dev
sudo apt install -y libopenblas0-pthread
sudo apt install -y libopenblas0
sudo apt install -y libopenexr-3-1-30
sudo apt install -y libopengl0
sudo apt install -y libopenh264-7
sudo apt install -y libopenjp2-7
sudo apt install -y libopenmpt-modplug1
sudo apt install -y libopenmpt0
sudo apt install -y libopenni2-0
sudo apt install -y libopus0
sudo apt install -y liborc-0.4-0
sudo apt install -y liborcus-0.17-0
sudo apt install -y liborcus-parser-0.17-0
sudo apt install -y libp11-kit0
sudo apt install -y libp8-platform2
sudo apt install -y libpackagekit-glib2-18
sudo apt install -y libpagemaker-0.0-0
sudo apt install -y libpam-cap
sudo apt install -y libpam-fprintd
sudo apt install -y libpam-gnome-keyring
sudo apt install -y libpam-modules-bin
sudo apt install -y libpam-modules
sudo apt install -y libpam-pwquality
sudo apt install -y libpam-runtime
sudo apt install -y libpam-sss
sudo apt install -y libpam-systemd
sudo apt install -y libpam0g
sudo apt install -y libpango-1.0-0
sudo apt install -y libpangocairo-1.0-0
sudo apt install -y libpangoft2-1.0-0
sudo apt install -y libpangomm-1.4-1v5
sudo apt install -y libpangoxft-1.0-0
sudo apt install -y libpaper-utils
sudo apt install -y libpaper1
sudo apt install -y libparted-fs-resize0
sudo apt install -y libparted2
sudo apt install -y libpath-utils1
sudo apt install -y libpathplan4
sudo apt install -y libpcap0.8
sudo apt install -y libpcaudio0
sudo apt install -y libpci3
sudo apt install -y libpciaccess0
sudo apt install -y libpcre2-16-0
sudo apt install -y libpcre2-32-0
sudo apt install -y libpcre2-8-0
sudo apt install -y libpcre2-dev
sudo apt install -y libpcre2-posix3
sudo apt install -y libpcre3
sudo apt install -y libpcrecpp0v5
sudo apt install -y libpcsclite1
sudo apt install -y libpeas-1.0-0
sudo apt install -y libpeas-common
sudo apt install -y libperl4-corelibs-perl
sudo apt install -y libperl5.36
sudo apt install -y libpgm-5.3-0
sudo apt install -y libphonenumber8
sudo apt install -y libpipeline1
sudo apt install -y libpipewire-0.3-0
sudo apt install -y libpipewire-0.3-common
sudo apt install -y libpipewire-0.3-modules
sudo apt install -y libpixman-1-0
sudo apt install -y libpkcs11-helper1
sudo apt install -y libpkgconf3
sudo apt install -y libplacebo208
sudo apt install -y libplist3
sudo apt install -y libplymouth5
sudo apt install -y libpmem1
sudo apt install -y libpng16-16
sudo apt install -y libpocketsphinx3
sudo apt install -y libpodofo0.9.8
sudo apt install -y libpolkit-agent-1-0
sudo apt install -y libpolkit-gobject-1-0
sudo apt install -y libpolkit-qt5-1-1
sudo apt install -y libpoppler-cpp0v5
sudo apt install -y libpoppler-glib8
sudo apt install -y libpoppler126
sudo apt install -y libpopt0
sudo apt install -y libportal-gtk3-1
sudo apt install -y libportal-gtk4-1
sudo apt install -y libportal1
sudo apt install -y libportaudio2
sudo apt install -y libportmidi0
sudo apt install -y libportsmf0v5
sudo apt install -y libpostproc56
sudo apt install -y libpotrace0
sudo apt install -y libppd2-common
sudo apt install -y libppd2
sudo apt install -y libpq5
sudo apt install -y libproc-waitstat-perl
sudo apt install -y libproc2-0
sudo apt install -y libproj25
sudo apt install -y libprotobuf-c1
sudo apt install -y libprotobuf-lite32
sudo apt install -y libprotobuf32
sudo apt install -y libproxy-tools
sudo apt install -y libproxy1-plugin-gsettings
sudo apt install -y libproxy1-plugin-networkmanager
sudo apt install -y libproxy1v5
sudo apt install -y libpsl5
sudo apt install -y libptexenc1
sudo apt install -y libpulse-mainloop-glib0
sudo apt install -y libpulse0
sudo apt install -y libpwquality-common
sudo apt install -y libpwquality1
sudo apt install -y libpython3-all-dev
sudo apt install -y libpython3-dev
sudo apt install -y libpython3-stdlib
sudo apt install -y libpython3.11-dev
sudo apt install -y libpython3.11-minimal
sudo apt install -y libpython3.11-stdlib
sudo apt install -y libpython3.11
sudo apt install -y libqca-qt5-2-plugins
sudo apt install -y libqca-qt5-2
sudo apt install -y libqhull-r8.0
sudo apt install -y libqmi-glib5
sudo apt install -y libqmi-proxy
sudo apt install -y libqmi-utils
sudo apt install -y libqpdf29
sudo apt install -y libqrencode4
sudo apt install -y libqt5core5a
sudo apt install -y libqt5dbus5
sudo apt install -y libqt5gui5
sudo apt install -y libqt5multimedia5-plugins
sudo apt install -y libqt5multimedia5
sudo apt install -y libqt5multimediagsttools5
sudo apt install -y libqt5multimediawidgets5
sudo apt install -y libqt5network5
sudo apt install -y libqt5positioning5
sudo apt install -y libqt5printsupport5
sudo apt install -y libqt5qml5
sudo apt install -y libqt5qmlmodels5
sudo apt install -y libqt5qmlworkerscript5
sudo apt install -y libqt5quick5
sudo apt install -y libqt5quickcontrols2-5
sudo apt install -y libqt5quicktemplates2-5
sudo apt install -y libqt5sensors5
sudo apt install -y libqt5svg5
sudo apt install -y libqt5texttospeech5
sudo apt install -y libqt5waylandclient5
sudo apt install -y libqt5waylandcompositor5
sudo apt install -y libqt5webchannel5
sudo apt install -y libqt5webkit5
sudo apt install -y libqt5widgets5
sudo apt install -y libqt5x11extras5
sudo apt install -y libqt5xdg3
sudo apt install -y libqt5xdgiconloader3
sudo apt install -y libqt5xml5
sudo apt install -y libqt6core6
sudo apt install -y libqt6dbus6
sudo apt install -y libqt6gui6
sudo apt install -y libqt6network6
sudo apt install -y libqt6opengl6
sudo apt install -y libqt6openglwidgets6
sudo apt install -y libqt6positioning6
sudo apt install -y libqt6printsupport6
sudo apt install -y libqt6qml6
sudo apt install -y libqt6qmlmodels6
sudo apt install -y libqt6quick6
sudo apt install -y libqt6quickwidgets6
sudo apt install -y libqt6sql6-sqlite
sudo apt install -y libqt6sql6
sudo apt install -y libqt6svg6
sudo apt install -y libqt6svgwidgets6
sudo apt install -y libqt6test6
sudo apt install -y libqt6waylandclient6
sudo apt install -y libqt6waylandcompositor6
sudo apt install -y libqt6waylandeglclienthwintegration6
sudo apt install -y libqt6waylandeglcompositorhwintegration6
sudo apt install -y libqt6webchannel6
sudo apt install -y libqt6webengine6-data
sudo apt install -y libqt6webenginecore6-bin
sudo apt install -y libqt6webenginecore6
sudo apt install -y libqt6webenginequick6
sudo apt install -y libqt6webenginewidgets6
sudo apt install -y libqt6widgets6
sudo apt install -y libqt6wlshellintegration6
sudo apt install -y libqt6xml6
sudo apt install -y libquadmath0
sudo apt install -y libquicktime2
sudo apt install -y librabbitmq4
sudo apt install -y librados2
sudo apt install -y libraptor2-0
sudo apt install -y libraqm0
sudo apt install -y librasqal3
sudo apt install -y librav1e0
sudo apt install -y libraw1394-11
sudo apt install -y librdf0
sudo apt install -y librdmacm1
sudo apt install -y libre2-10
sudo apt install -y libreadline8
sudo apt install -y librecode0
sudo apt install -y libref-array1
sudo apt install -y libreoffice-base-core
sudo apt install -y libreoffice-calc
sudo apt install -y libreoffice-common
sudo apt install -y libreoffice-core
sudo apt install -y libreoffice-draw
sudo apt install -y libreoffice-gnome
sudo apt install -y libreoffice-gtk3
sudo apt install -y libreoffice-help-common
sudo apt install -y libreoffice-help-en-us
sudo apt install -y libreoffice-impress
sudo apt install -y libreoffice-math
sudo apt install -y libreoffice-style-colibre
sudo apt install -y libreoffice-style-elementary
sudo apt install -y libreoffice-style-yaru
sudo apt install -y libreoffice-writer
sudo apt install -y libresid-builder0c2a
sudo apt install -y librest-1.0-0
sudo apt install -y librevenge-0.0-0
sudo apt install -y librhash0
sudo apt install -y librist4
sudo apt install -y librsvg2-2
sudo apt install -y librsvg2-common
sudo apt install -y librsync2
sudo apt install -y librsyntaxtextarea-java
sudo apt install -y librtmp1
sudo apt install -y librttopo1
sudo apt install -y librubberband2
sudo apt install -y libruby3.1
sudo apt install -y libruby
sudo apt install -y librxtx-java
sudo apt install -y librygel-core-2.8-0
sudo apt install -y librygel-db-2.8-0
sudo apt install -y librygel-renderer-2.8-0
sudo apt install -y librygel-server-2.8-0
sudo apt install -y libsamplerate0
sudo apt install -y libsane-common
sudo apt install -y libsane1
sudo apt install -y libsasl2-2
sudo apt install -y libsasl2-modules-db
sudo apt install -y libsasl2-modules-gssapi-mit
sudo apt install -y libsasl2-modules
sudo apt install -y libsbc1
sudo apt install -y libsbsms10
sudo apt install -y libsdl-image1.2
sudo apt install -y libsdl1.2debian
sudo apt install -y libsdl2-2.0-0
sudo apt install -y libseccomp2
sudo apt install -y libsecret-1-0
sudo apt install -y libsecret-common
sudo apt install -y libselinux1-dev
sudo apt install -y libselinux1
sudo apt install -y libsemanage-common
sudo apt install -y libsemanage2
sudo apt install -y libsemver-java
sudo apt install -y libsensors-config
sudo apt install -y libsensors5
sudo apt install -y libsepol-dev
sudo apt install -y libsepol2
sudo apt install -y libserd-0-0
sudo apt install -y libserf-1-1
sudo apt install -y libserialport0
sudo apt install -y libshairplay0
sudo apt install -y libshine3
sudo apt install -y libshout3
sudo apt install -y libsidplay2
sudo apt install -y libsigc++-2.0-0v5
sudo apt install -y libsigsegv2
sudo apt install -y libslang2
sudo apt install -y libslf4j-java
sudo apt install -y libsm6
sudo apt install -y libsmartcols1
sudo apt install -y libsmbclient
sudo apt install -y libsmbios-c2
sudo apt install -y libsmi2ldbl
sudo apt install -y libsnapd-glib-2-1
sudo apt install -y libsnappy1v5
sudo apt install -y libsndfile1
sudo apt install -y libsndio7.0
sudo apt install -y libsnmp-base
sudo apt install -y libsnmp40
sudo apt install -y libsocket6-perl
sudo apt install -y libsodium23
sudo apt install -y libsonic0
sudo apt install -y libsord-0-0
sudo apt install -y libsoundtouch1
sudo apt install -y libsoup-3.0-0
sudo apt install -y libsoup-3.0-common
sudo apt install -y libsoup2.4-1
sudo apt install -y libsoup2.4-common
sudo apt install -y libsource-highlight-common
sudo apt install -y libsource-highlight4v5
sudo apt install -y libsoxr0
sudo apt install -y libspa-0.2-bluetooth
sudo apt install -y libspa-0.2-modules
sudo apt install -y libspandsp2
sudo apt install -y libspatialaudio0
sudo apt install -y libspatialite7
sudo apt install -y libspdlog1.10
sudo apt install -y libspectre1
sudo apt install -y libspeechd2
sudo apt install -y libspeex1
sudo apt install -y libspeexdsp1
sudo apt install -y libsphinxbase3
sudo apt install -y libsqlite3-0
sudo apt install -y libsratom-0-0
sudo apt install -y libsrt1.5-gnutls
sudo apt install -y libsrtp2-1
sudo apt install -y libss2
sudo apt install -y libssh-4
sudo apt install -y libssh-gcrypt-4
sudo apt install -y libssh2-1
sudo apt install -y libssl-dev
sudo apt install -y libssl3
sudo apt install -y libssl3
sudo apt install -y libsss-certmap0
sudo apt install -y libsss-idmap0
sudo apt install -y libsss-nss-idmap0
sudo apt install -y libstartup-notification0
sudo apt install -y libstdc++-12-dev
sudo apt install -y libstdc++6
sudo apt install -y libstemmer0d
sudo apt install -y libsuil-0-0
sudo apt install -y libsuitesparseconfig5
sudo apt install -y libsuperlu5
sudo apt install -y libsvn1
sudo apt install -y libsvtav1enc1
sudo apt install -y libswresample4
sudo apt install -y libswscale6
sudo apt install -y libsynctex2
sudo apt install -y libsys-hostname-long-perl
sudo apt install -y libsysmetrics1
sudo apt install -y libsystemd-shared
sudo apt install -y libsystemd0
sudo apt install -y libsystemd0
sudo apt install -y libsz2
sudo apt install -y libtag1v5-vanilla
sudo apt install -y libtag1v5
sudo apt install -y libtalloc2
sudo apt install -y libtasn1-6
sudo apt install -y libtcl8.6
sudo apt install -y libtdb1
sudo apt install -y libteamdctl0
sudo apt install -y libteckit0
sudo apt install -y libtepl-6-2
sudo apt install -y libtepl-common
sudo apt install -y libterm-readkey-perl
sudo apt install -y libtevent0
sudo apt install -y libtexlua53-5
sudo apt install -y libtexluajit2
sudo apt install -y libtext-charwidth-perl
sudo apt install -y libtext-iconv-perl
sudo apt install -y libtext-wrapi18n-perl
sudo apt install -y libthai-data
sudo apt install -y libthai0
sudo apt install -y libtheora0
sudo apt install -y libtiff6
sudo apt install -y libtimedate-perl
sudo apt install -y libtinfo6
sudo apt install -y libtinyxml2.6.2v5
sudo apt install -y libtirpc-common
sudo apt install -y libtirpc-dev
sudo apt install -y libtirpc3
sudo apt install -y libtirpc3
sudo apt install -y libtk8.6
sudo apt install -y libtotem-plparser-common
sudo apt install -y libtotem-plparser18
sudo apt install -y libtotem0
sudo apt install -y libtracker-sparql-3.0-0
sudo apt install -y libts0
sudo apt install -y libtsan0
sudo apt install -y libtsan2
sudo apt install -y libtss2-esys-3.0.2-0
sudo apt install -y libtss2-mu0
sudo apt install -y libtss2-rc0
sudo apt install -y libtss2-sys1
sudo apt install -y libtss2-tcti-cmd0
sudo apt install -y libtss2-tcti-device0
sudo apt install -y libtss2-tcti-mssim0
sudo apt install -y libtss2-tcti-swtpm0
sudo apt install -y libtss2-tctildr0
sudo apt install -y libturbojpeg
sudo apt install -y libtwolame0
sudo apt install -y libtypes-serialiser-perl
sudo apt install -y libu2f-udev
sudo apt install -y libubsan1
sudo apt install -y libuchardet0
sudo apt install -y libudev1
sudo apt install -y libudf0
sudo apt install -y libudfread0
sudo apt install -y libudisks2-0
sudo apt install -y libunistring2
sudo apt install -y libunistring2
sudo apt install -y libunity-protocol-private0
sudo apt install -y libunity-scopes-json-def-desktop
sudo apt install -y libunity9
sudo apt install -y libunix-syslog-perl
sudo apt install -y libuno-cppu3
sudo apt install -y libuno-cppuhelpergcc3-3
sudo apt install -y libuno-purpenvhelpergcc3-3
sudo apt install -y libuno-sal3
sudo apt install -y libuno-salhelpergcc3-3
sudo apt install -y libunwind8
sudo apt install -y libupnp13
sudo apt install -y libupower-glib3
sudo apt install -y liburi-perl
sudo apt install -y liburing2
sudo apt install -y liburiparser1
sudo apt install -y libusb-0.1-4
sudo apt install -y libusb-1.0-0
sudo apt install -y libusbmuxd6
sudo apt install -y libutempter0
sudo apt install -y libutf8proc2
sudo apt install -y libuuid1
sudo apt install -y libuv1
sudo apt install -y libv4l-0
sudo apt install -y libv4lconvert0
sudo apt install -y libva-drm2
sudo apt install -y libva-wayland2
sudo apt install -y libva-x11-2
sudo apt install -y libva2
sudo apt install -y libvamp-hostsdk3v5
sudo apt install -y libvdpau1
sudo apt install -y libvidstab1.1
sudo apt install -y libvisio-0.1-1
sudo apt install -y libvisual-0.4-0
sudo apt install -y libvlc-bin
sudo apt install -y libvlc5
sudo apt install -y libvlccore9
sudo apt install -y libvncclient1
sudo apt install -y libvo-aacenc0
sudo apt install -y libvo-amrwbenc0
sudo apt install -y libvoikko1
sudo apt install -y libvolume-key1
sudo apt install -y libvorbis0a
sudo apt install -y libvorbisenc2
sudo apt install -y libvorbisfile3
sudo apt install -y libvorbisidec1
sudo apt install -y libvpx7
sudo apt install -y libvte-2.91-0
sudo apt install -y libvte-2.91-common
sudo apt install -y libvulkan1
sudo apt install -y libwacom-common
sudo apt install -y libwacom9
sudo apt install -y libwavpack1
sudo apt install -y libwayland-client++1
sudo apt install -y libwayland-client0
sudo apt install -y libwayland-cursor++1
sudo apt install -y libwayland-cursor0
sudo apt install -y libwayland-egl++1
sudo apt install -y libwayland-egl1
sudo apt install -y libwayland-server0
sudo apt install -y libwbclient0
sudo apt install -y libwebkit2gtk-4.1-0
sudo apt install -y libwebkitgtk-6.0-4
sudo apt install -y libwebp7
sudo apt install -y libwebpdemux2
sudo apt install -y libwebpmux3
sudo apt install -y libwebrtc-audio-processing1
sudo apt install -y libwget0
sudo apt install -y libwhoopsie-preferences0
sudo apt install -y libwhoopsie0
sudo apt install -y libwildmidi2
sudo apt install -y libwinpr2-2
sudo apt install -y libwireplumber-0.4-0
sudo apt install -y libwireshark-data
sudo apt install -y libwireshark16
sudo apt install -y libwiretap13
sudo apt install -y libwmf-0.2-7-gtk
sudo apt install -y libwmf-0.2-7
sudo apt install -y libwmf0.2-7-gtk
sudo apt install -y libwmflite-0.2-7
sudo apt install -y libwnck-3-0
sudo apt install -y libwnck-3-common
sudo apt install -y libwoff1
sudo apt install -y libwpd-0.10-10
sudo apt install -y libwpe-1.0-1
sudo apt install -y libwpebackend-fdo-1.0-1
sudo apt install -y libwpg-0.3-3
sudo apt install -y libwps-0.4-4
sudo apt install -y libwrap0
sudo apt install -y libwsutil14
sudo apt install -y libwxbase3.2-1
sudo apt install -y libwxgtk-gl3.2-1
sudo apt install -y libwxgtk3.2-1
sudo apt install -y libx11-6
sudo apt install -y libx11-data
sudo apt install -y libx11-protocol-perl
sudo apt install -y libx11-xcb1
sudo apt install -y libx264-164
sudo apt install -y libx265-199
sudo apt install -y libxapian30
sudo apt install -y libxau6
sudo apt install -y libxaw7
sudo apt install -y libxcb-composite0
sudo apt install -y libxcb-damage0
sudo apt install -y libxcb-dri2-0
sudo apt install -y libxcb-dri3-0
sudo apt install -y libxcb-glx0
sudo apt install -y libxcb-icccm4
sudo apt install -y libxcb-image0
sudo apt install -y libxcb-keysyms1
sudo apt install -y libxcb-present0
sudo apt install -y libxcb-randr0
sudo apt install -y libxcb-record0
sudo apt install -y libxcb-render-util0
sudo apt install -y libxcb-render0
sudo apt install -y libxcb-res0
sudo apt install -y libxcb-shape0
sudo apt install -y libxcb-shm0
sudo apt install -y libxcb-sync1
sudo apt install -y libxcb-util1
sudo apt install -y libxcb-xfixes0
sudo apt install -y libxcb-xinerama0
sudo apt install -y libxcb-xinput0
sudo apt install -y libxcb-xkb1
sudo apt install -y libxcb-xv0
sudo apt install -y libxcb1
sudo apt install -y libxcomposite1
sudo apt install -y libxcursor1
sudo apt install -y libxcvt0
sudo apt install -y libxdamage1
sudo apt install -y libxdmcp6
sudo apt install -y libxdo3
sudo apt install -y libxerces-c3.2
sudo apt install -y libxext6
sudo apt install -y libxfixes3
sudo apt install -y libxfont2
sudo apt install -y libxft2
sudo apt install -y libxi6
sudo apt install -y libxinerama1
sudo apt install -y libxkbcommon-x11-0
sudo apt install -y libxkbcommon0
sudo apt install -y libxkbfile1
sudo apt install -y libxkbregistry0
sudo apt install -y libxklavier16
sudo apt install -y libxml++2.6-2v5
sudo apt install -y libxml-commons-external-java
sudo apt install -y libxml2-utils
sudo apt install -y libxml2
sudo apt install -y libxmlb2
sudo apt install -y libxmlgraphics-commons-java
sudo apt install -y libxmlrpc-epi0
sudo apt install -y libxmlsec1-nss
sudo apt install -y libxmlsec1
sudo apt install -y libxmu6
sudo apt install -y libxmuu1
sudo apt install -y libxpm4
sudo apt install -y libxrandr2
sudo apt install -y libxrender1
sudo apt install -y libxres1
sudo apt install -y libxshmfence1
sudo apt install -y libxsimd-dev
sudo apt install -y libxslt1.1
sudo apt install -y libxss1
sudo apt install -y libxt6
sudo apt install -y libxtables12
sudo apt install -y libxtst6
sudo apt install -y libxv1
sudo apt install -y libxvidcore4
sudo apt install -y libxvmc1
sudo apt install -y libxxf86dga1
sudo apt install -y libxxf86vm1
sudo apt install -y libxxhash0
sudo apt install -y libyajl2
sudo apt install -y libyaml-0-2
sudo apt install -y libyelp0
sudo apt install -y libzbar0
sudo apt install -y libzimg2
sudo apt install -y libzip4
sudo apt install -y libzita-alsa-pcmi0
sudo apt install -y libzita-resampler1
sudo apt install -y libzmq5
sudo apt install -y libzstd1
sudo apt install -y libzstd1
sudo apt install -y libzvbi-common
sudo apt install -y libzvbi0
sudo apt install -y libzxing2
sudo apt install -y libzzip-0-13
sudo apt install -y linux-base
sudo apt install -y linux-firmware
sudo apt install -y linux-headers-6.2.0-26-generic
sudo apt install -y linux-headers-6.2.0-26
sudo apt install -y linux-image-6.2.0-26-generic
sudo apt install -y linux-libc-dev
sudo apt install -y linux-modules-6.2.0-26-generic
sudo apt install -y linux-modules-extra-6.2.0-26-generic
sudo apt install -y linux-sound-base
sudo apt install -y lmodern
sudo apt install -y locales
sudo apt install -y lockfile-progs
sudo apt install -y logcheck-database
sudo apt install -y logcheck
sudo apt install -y login
sudo apt install -y logrotate
sudo apt install -y logsave
sudo apt install -y logtail
sudo apt install -y lp-solve
sudo apt install -y lrzsz
sudo apt install -y lsb-base
sudo apt install -y lsb-release
sudo apt install -y lshw
sudo apt install -y lsof
sudo apt install -y lto-disabled-list
sudo apt install -y lua-lpeg
sudo apt install -y lynx-common
sudo apt install -y lynx
sudo apt install -y m4
sudo apt install -y mailcap
sudo apt install -y mailutils-common
sudo apt install -y mailutils
sudo apt install -y make
sudo apt install -y man-db
sudo apt install -y man2html-base
sudo apt install -y man2html
sudo apt install -y manpages-dev
sudo apt install -y manpages
sudo apt install -y mapcache-cgi
sudo apt install -y mariadb-client-core
sudo apt install -y mariadb-client
sudo apt install -y mariadb-common
sudo apt install -y mariadb-plugin-provider-bzip2
sudo apt install -y mariadb-plugin-provider-lz4
sudo apt install -y mariadb-plugin-provider-lzma
sudo apt install -y mariadb-plugin-provider-lzo
sudo apt install -y mariadb-plugin-provider-snappy
sudo apt install -y mariadb-server-core
sudo apt install -y mariadb-server
sudo apt install -y mawk
sudo apt install -y mdadm
sudo apt install -y media-player-info
sudo apt install -y media-types
sudo apt install -y medusa
sudo apt install -y meld
sudo apt install -y memtest86+
sudo apt install -y mesa-utils-bin
sudo apt install -y mesa-utils
sudo apt install -y mesa-va-drivers
sudo apt install -y mesa-vdpau-drivers
sudo apt install -y mesa-vulkan-drivers
sudo apt install -y mime-construct
sudo apt install -y mime-support
sudo apt install -y minicom
sudo apt install -y mobile-broadband-provider-info
sudo apt install -y modemmanager
sudo apt install -y mokutil
sudo apt install -y mount
sudo apt install -y mousetweaks
sudo apt install -y mplayer
sudo apt install -y mtr-tiny
sudo apt install -y mupdf-tools
sudo apt install -y mutter-common-bin
sudo apt install -y mutter-common
sudo apt install -y mutter
sudo apt install -y mysql-common
sudo apt install -y mythes-en-us
sudo apt install -y nano
sudo apt install -y nautilus-data
sudo apt install -y nautilus-extension-gnome-terminal
sudo apt install -y nautilus
sudo apt install -y ncal
sudo apt install -y ncurses-base
sudo apt install -y ncurses-bin
sudo apt install -y ncurses-term
sudo apt install -y net-tools
sudo apt install -y netbase
sudo apt install -y netcat-openbsd
sudo apt install -y netpbm
sudo apt install -y netplan.io
sudo apt install -y network-manager-config-connectivity-ubuntu
sudo apt install -y network-manager-gnome
sudo apt install -y network-manager-openvpn-gnome
sudo apt install -y network-manager-openvpn
sudo apt install -y network-manager-pptp-gnome
sudo apt install -y network-manager-pptp
sudo apt install -y network-manager
sudo apt install -y networkd-dispatcher
sudo apt install -y nftables
sudo apt install -y nmap-common
sudo apt install -y nmap
sudo apt install -y node-html5shiv
sudo apt install -y ntfs-3g
sudo apt install -y ocl-icd-libopencl1
sudo apt install -y openjdk-17-jre-headless
sudo apt install -y openjdk-17-jre
sudo apt install -y openprinting-ppds
sudo apt install -y openssh-client
sudo apt install -y openssh-server
sudo apt install -y openssh-sftp-server
sudo apt install -y openssl
sudo apt install -y openvpn
sudo apt install -y optipng
sudo apt install -y orca
sudo apt install -y os-prober
sudo apt install -y p11-kit-modules
sudo apt install -y p11-kit
sudo apt install -y p7zip-full
sudo apt install -y p7zip
sudo apt install -y packagekit-tools
sudo apt install -y packagekit
sudo apt install -y parted
sudo apt install -y passwd
sudo apt install -y pastebinit
sudo apt install -y patch
sudo apt install -y pax
sudo apt install -y pci.ids
sudo apt install -y pciutils
sudo apt install -y pcmciautils
sudo apt install -y pdf2djvu
sudo apt install -y perl-base
sudo apt install -y perl-modules-5.36
sudo apt install -y perl-openssl-defaults
sudo apt install -y perl
sudo apt install -y php-common
sudo apt install -y php-curl
sudo apt install -y php-gd
sudo apt install -y php-intl
sudo apt install -y php-mbstring
sudo apt install -y php-mysql
sudo apt install -y php-soap
sudo apt install -y php-xml
sudo apt install -y php-xmlrpc
sudo apt install -y php-zip
sudo apt install -y php8.1-cli
sudo apt install -y php8.1-common
sudo apt install -y php8.1-curl
sudo apt install -y php8.1-fpm
sudo apt install -y php8.1-gd
sudo apt install -y php8.1-intl
sudo apt install -y php8.1-mbstring
sudo apt install -y php8.1-mysql
sudo apt install -y php8.1-opcache
sudo apt install -y php8.1-readline
sudo apt install -y php8.1-soap
sudo apt install -y php8.1-xml
sudo apt install -y php8.1-xmlrpc
sudo apt install -y php8.1-zip
sudo apt install -y pigz
sudo apt install -y pinentry-curses
sudo apt install -y pinentry-gnome3
sudo apt install -y pinot
sudo apt install -y pipewire-alsa
sudo apt install -y pipewire-audio
sudo apt install -y pipewire-bin
sudo apt install -y pipewire-pulse
sudo apt install -y pipewire
sudo apt install -y pkexec
sudo apt install -y pkg-config
sudo apt install -y pkgconf-bin
sudo apt install -y pkgconf
sudo apt install -y plocate
sudo apt install -y plymouth-label
sudo apt install -y plymouth-theme-spinner
sudo apt install -y plymouth-theme-ubuntu-text
sudo apt install -y plymouth
sudo apt install -y po-debconf
sudo apt install -y pocketsphinx-en-us
sudo apt install -y policykit-1
sudo apt install -y policykit-desktop-privileges
sudo apt install -y polkitd
sudo apt install -y poppler-data
sudo apt install -y poppler-utils
sudo apt install -y postfix
sudo apt install -y postgresql-client-15
sudo apt install -y postgresql-client-common
sudo apt install -y potrace
sudo apt install -y power-profiles-daemon
sudo apt install -y powermgmt-base
sudo apt install -y ppp
sudo apt install -y pptp-linux
sudo apt install -y printer-driver-all
sudo apt install -y printer-driver-brlaser
sudo apt install -y printer-driver-c2050
sudo apt install -y printer-driver-c2esp
sudo apt install -y printer-driver-cjet
sudo apt install -y printer-driver-dymo
sudo apt install -y printer-driver-escpr
sudo apt install -y printer-driver-fujixerox
sudo apt install -y printer-driver-indexbraille
sudo apt install -y printer-driver-m2300w
sudo apt install -y printer-driver-min12xxw
sudo apt install -y printer-driver-oki
sudo apt install -y printer-driver-pnm2ppa
sudo apt install -y printer-driver-postscript-hp
sudo apt install -y printer-driver-ptouch
sudo apt install -y printer-driver-pxljr
sudo apt install -y printer-driver-sag-gdi
sudo apt install -y procps
sudo apt install -y proj-bin
sudo apt install -y proj-data
sudo apt install -y psmisc
sudo apt install -y publicsuffix
sudo apt install -y puredata-core
sudo apt install -y puredata-dev
sudo apt install -y puredata-doc
sudo apt install -y puredata-extra
sudo apt install -y puredata-gui-l10n
sudo apt install -y puredata-gui
sudo apt install -y puredata-utils
sudo apt install -y puredata
sudo apt install -y pv
sudo apt install -y pyqt6-dev-tools
sudo apt install -y python-apt-common
sudo apt install -y python3-acme
sudo apt install -y python3-all-dev
sudo apt install -y python3-all
sudo apt install -y python3-appdirs
sudo apt install -y python3-apsw
sudo apt install -y python3-apt
sudo apt install -y python3-aptdaemon.gtk3widgets
sudo apt install -y python3-aptdaemon
sudo apt install -y python3-asttokens
sudo apt install -y python3-async-timeout
sudo apt install -y python3-attr
sudo apt install -y python3-backcall
sudo apt install -y python3-bcrypt
sudo apt install -y python3-beniget
sudo apt install -y python3-blinker
sudo apt install -y python3-brlapi
sudo apt install -y python3-brotli
sudo apt install -y python3-bs4
sudo apt install -y python3-cairo
sudo apt install -y python3-certbot
sudo apt install -y python3-certifi
sudo apt install -y python3-cffi-backend
sudo apt install -y python3-chardet
sudo apt install -y python3-charset-normalizer
sudo apt install -y python3-chm
sudo apt install -y python3-click
sudo apt install -y python3-colorama
sudo apt install -y python3-commandnotfound
sudo apt install -y python3-configargparse
sudo apt install -y python3-configobj
sudo apt install -y python3-cryptography
sudo apt install -y python3-css-parser
sudo apt install -y python3-cssselect
sudo apt install -y python3-cups
sudo apt install -y python3-cupshelpers
sudo apt install -y python3-dateutil
sudo apt install -y python3-dbus
sudo apt install -y python3-debconf
sudo apt install -y python3-debian
sudo apt install -y python3-decorator
sudo apt install -y python3-defer
sudo apt install -y python3-dev
sudo apt install -y python3-distro-info
sudo apt install -y python3-distro
sudo apt install -y python3-distutils
sudo apt install -y python3-dnspython
sudo apt install -y python3-docutils
sudo apt install -y python3-executing
sudo apt install -y python3-fasteners
sudo apt install -y python3-feedparser
sudo apt install -y python3-fonttools
sudo apt install -y python3-fs
sudo apt install -y python3-future
sudo apt install -y python3-gast
sudo apt install -y python3-gdbm
sudo apt install -y python3-gi-cairo
sudo apt install -y python3-gi
sudo apt install -y python3-gpg
sudo apt install -y python3-html2text
sudo apt install -y python3-html5-parser
sudo apt install -y python3-html5lib
sudo apt install -y python3-httplib2
sudo apt install -y python3-ibus-1.0
sudo apt install -y python3-icu
sudo apt install -y python3-idna
sudo apt install -y python3-ifaddr
sudo apt install -y python3-importlib-metadata
sudo apt install -y python3-ipython
sudo apt install -y python3-jaraco.classes
sudo apt install -y python3-jedi
sudo apt install -y python3-jeepney
sudo apt install -y python3-josepy
sudo apt install -y python3-jwt
sudo apt install -y python3-keyring
sudo apt install -y python3-launchpadlib
sudo apt install -y python3-lazr.restfulclient
sudo apt install -y python3-lazr.uri
sudo apt install -y python3-ldb
sudo apt install -y python3-lib2to3
sudo apt install -y python3-lockfile
sudo apt install -y python3-louis
sudo apt install -y python3-lxml
sudo apt install -y python3-lz4
sudo apt install -y python3-markdown-it
sudo apt install -y python3-markdown
sudo apt install -y python3-matplotlib-inline
sudo apt install -y python3-mdurl
sudo apt install -y python3-mechanize
sudo apt install -y python3-minimal
sudo apt install -y python3-monotonic
sudo apt install -y python3-more-itertools
sudo apt install -y python3-mpmath
sudo apt install -y python3-msgpack
sudo apt install -y python3-nacl
sudo apt install -y python3-netifaces
sudo apt install -y python3-newt
sudo apt install -y python3-numpy
sudo apt install -y python3-oauthlib
sudo apt install -y python3-olefile
sudo apt install -y python3-openssl
sudo apt install -y python3-paramiko
sudo apt install -y python3-parsedatetime
sudo apt install -y python3-parso
sudo apt install -y python3-pdfminer
sudo apt install -y python3-pexpect
sudo apt install -y python3-pickleshare
sudo apt install -y python3-pil.imagetk
sudo apt install -y python3-pil
sudo apt install -y python3-pip
sudo apt install -y python3-pkg-resources
sudo apt install -y python3-ply
sudo apt install -y python3-prompt-toolkit
sudo apt install -y python3-psutil
sudo apt install -y python3-ptyprocess
sudo apt install -y python3-pure-eval
sudo apt install -y python3-py7zr
sudo apt install -y python3-pyatspi
sudo apt install -y python3-pycryptodome
sudo apt install -y python3-pygments
sudo apt install -y python3-pyparsing
sudo apt install -y python3-pyqt6.qtqml
sudo apt install -y python3-pyqt6.qtquick
sudo apt install -y python3-pyqt6.qtsvg
sudo apt install -y python3-pyqt6.qtwebchannel
sudo apt install -y python3-pyqt6.qtwebengine
sudo apt install -y python3-pyqt6.sip
sudo apt install -y python3-pyqt6
sudo apt install -y python3-pythran
sudo apt install -y python3-regex
sudo apt install -y python3-repoze.lru
sudo apt install -y python3-requests
sudo apt install -y python3-rfc3339
sudo apt install -y python3-rich
sudo apt install -y python3-roman
sudo apt install -y python3-routes
sudo apt install -y python3-samba
sudo apt install -y python3-scipy
sudo apt install -y python3-secretstorage
sudo apt install -y python3-setuptools
sudo apt install -y python3-sgmllib3k
sudo apt install -y python3-six
sudo apt install -y python3-software-properties
sudo apt install -y python3-soupsieve
sudo apt install -y python3-speechd
sudo apt install -y python3-sss
sudo apt install -y python3-stack-data
sudo apt install -y python3-sympy
sudo apt install -y python3-talloc
sudo apt install -y python3-tdb
sudo apt install -y python3-texttable
sudo apt install -y python3-tk
sudo apt install -y python3-traitlets
sudo apt install -y python3-tz
sudo apt install -y python3-ufolib2
sudo apt install -y python3-uno
sudo apt install -y python3-urllib3
sudo apt install -y python3-wadllib
sudo apt install -y python3-wcwidth
sudo apt install -y python3-webencodings
sudo apt install -y python3-webob
sudo apt install -y python3-wheel
sudo apt install -y python3-wxgtk4.0
sudo apt install -y python3-xdg
sudo apt install -y python3-xkit
sudo apt install -y python3-yaml
sudo apt install -y python3-zeroconf
sudo apt install -y python3-zipp
sudo apt install -y python3.11-dev
sudo apt install -y python3.11-minimal
sudo apt install -y python3.11
sudo apt install -y python3
sudo apt install -y qjackctl
sudo apt install -y qml-module-org-kde-kirigami2
sudo apt install -y qml-module-org-kde-kquickcontrolsaddons
sudo apt install -y qml-module-org-kde-newstuff
sudo apt install -y qml-module-qt-labs-folderlistmodel
sudo apt install -y qml-module-qt-labs-platform
sudo apt install -y qml-module-qt-labs-settings
sudo apt install -y qml-module-qtgraphicaleffects
sudo apt install -y qml-module-qtqml-models2
sudo apt install -y qml-module-qtqml
sudo apt install -y qml-module-qtquick-controls2
sudo apt install -y qml-module-qtquick-controls
sudo apt install -y qml-module-qtquick-dialogs
sudo apt install -y qml-module-qtquick-extras
sudo apt install -y qml-module-qtquick-layouts
sudo apt install -y qml-module-qtquick-privatewidgets
sudo apt install -y qml-module-qtquick-templates2
sudo apt install -y qml-module-qtquick-window2
sudo apt install -y qml-module-qtquick2
sudo apt install -y qt5-gtk-platformtheme
sudo apt install -y qt5dxcb-plugin
sudo apt install -y qt6-gtk-platformtheme
sudo apt install -y qt6-image-formats-plugins
sudo apt install -y qt6-qpa-plugins
sudo apt install -y qt6-translations-l10n
sudo apt install -y qt6-wayland
sudo apt install -y qtspeech5-speechd-plugin
sudo apt install -y qttranslations5-l10n
sudo apt install -y qtwayland5
sudo apt install -y rake
sudo apt install -y readline-common
sudo apt install -y realvnc-vnc-viewer
sudo apt install -y rfkill
sudo apt install -y riseup-vpn
sudo apt install -y rpcsvc-proto
sudo apt install -y rsync
sudo apt install -y rsyslog
sudo apt install -y rtkit
sudo apt install -y ruby-net-telnet
sudo apt install -y ruby-rubygems
sudo apt install -y ruby-sdbm
sudo apt install -y ruby-webrick
sudo apt install -y ruby-xmlrpc
sudo apt install -y ruby3.1
sudo apt install -y ruby
sudo apt install -y rubygems-integration
sudo apt install -y run-one
sudo apt install -y runc
sudo apt install -y rygel
sudo apt install -y samba-ad-provision
sudo apt install -y samba-common-bin
sudo apt install -y samba-common
sudo apt install -y samba-dsdb-modules
sudo apt install -y samba-libs
sudo apt install -y samba-vfs-modules
sudo apt install -y samba
sudo apt install -y sane-airscan
sudo apt install -y sane-utils
sudo apt install -y sbsigntool
sudo apt install -y screen
sudo apt install -y seahorse
sudo apt install -y secureboot-db
sudo apt install -y sed
sudo apt install -y sensible-utils
sudo apt install -y session-migration
sudo apt install -y setserial
sudo apt install -y sgml-base
sudo apt install -y sgml-data
sudo apt install -y shared-mime-info
sudo apt install -y shellinabox
sudo apt install -y shim-signed
sudo apt install -y simple-scan
sudo apt install -y smartmontools
sudo apt install -y snap
sudo apt install -y snapd
sudo apt install -y socat
sudo apt install -y software-properties-common
sudo apt install -y software-properties-gtk
sudo apt install -y sonnet-plugins
sudo apt install -y sound-icons
sudo apt install -y sound-theme-freedesktop
sudo apt install -y speech-dispatcher-audio-plugins
sudo apt install -y speech-dispatcher-espeak-ng
sudo apt install -y speech-dispatcher
sudo apt install -y spice-vdagent
sudo apt install -y squashfs-tools
sudo apt install -y sse3-support
sudo apt install -y ssh
sudo apt install -y sshfs
sudo apt install -y ssl-cert
sudo apt install -y sssd-ad-common
sudo apt install -y sssd-ad
sudo apt install -y sssd-common
sudo apt install -y sssd-ipa
sudo apt install -y sssd-krb5-common
sudo apt install -y sssd-krb5
sudo apt install -y sssd-ldap
sudo apt install -y sssd-proxy
sudo apt install -y sssd
sudo apt install -y strace
sudo apt install -y sudo
sudo apt install -y switcheroo-control
sudo apt install -y synaptic
sudo apt install -y system-config-printer-common
sudo apt install -y system-config-printer-udev
sudo apt install -y system-config-printer
sudo apt install -y systemd-hwe-hwdb
sudo apt install -y systemd-oomd
sudo apt install -y systemd-resolved
sudo apt install -y systemd-sysv
sudo apt install -y systemd-timesyncd
sudo apt install -y systemd
sudo apt install -y sysvinit-utils
sudo apt install -y t1utils
sudo apt install -y tar
sudo apt install -y tcl8.6
sudo apt install -y tcl
sudo apt install -y tcpdump
sudo apt install -y tdb-tools
sudo apt install -y tealdeer
sudo apt install -y telnet
sudo apt install -y terminator
sudo apt install -y tex-common
sudo apt install -y tex-gyre
sudo apt install -y texlive-base
sudo apt install -y texlive-binaries
sudo apt install -y texlive-fonts-recommended
sudo apt install -y texlive-latex-base
sudo apt install -y tftpd-hpa
sudo apt install -y time
sudo apt install -y timgm6mb-soundfont
sudo apt install -y tipa
sudo apt install -y tk8.6-blt2.5
sudo apt install -y tk8.6
sudo apt install -y tk
sudo apt install -y tmux
sudo apt install -y tnftp
sudo apt install -y totem-common
sudo apt install -y totem-plugins
sudo apt install -y totem
sudo apt install -y tpm-udev
sudo apt install -y tracker-extract
sudo apt install -y tracker-miner-fs
sudo apt install -y tracker
sudo apt install -y transmission-common
sudo apt install -y transmission-gtk
sudo apt install -y tripwire
sudo apt install -y tzdata-icu
sudo apt install -y tzdata
sudo apt install -y ubuntu-advantage-desktop-daemon
sudo apt install -y ubuntu-advantage-tools
sudo apt install -y ubuntu-docs
sudo apt install -y ubuntu-drivers-common
sudo apt install -y ubuntu-fan
sudo apt install -y ubuntu-keyring
sudo apt install -y ubuntu-minimal
sudo apt install -y ubuntu-mono
sudo apt install -y ubuntu-report
sudo apt install -y ubuntu-session
sudo apt install -y ubuntu-settings
sudo apt install -y ubuntu-standard
sudo apt install -y ubuntu-wallpapers-lunar
sudo apt install -y ubuntu-wallpapers
sudo apt install -y ucf
sudo apt install -y udev
sudo apt install -y udisks2
sudo apt install -y ufw
sudo apt install -y unattended-upgrades
sudo apt install -y unicode-data
sudo apt install -y unixodbc-common
sudo apt install -y uno-libs-private
sudo apt install -y unrtf
sudo apt install -y unzip
sudo apt install -y update-inetd
sudo apt install -y upower
sudo apt install -y ure
sudo apt install -y usb-creator-common
sudo apt install -y usb-creator-gtk
sudo apt install -y usb-modeswitch-data
sudo apt install -y usb-modeswitch
sudo apt install -y usb.ids
sudo apt install -y usbmuxd
sudo apt install -y usbutils
sudo apt install -y usrmerge
sudo apt install -y util-linux-extra
sudo apt install -y util-linux
sudo apt install -y uuid-dev
sudo apt install -y uuid-runtime
sudo apt install -y va-driver-all
sudo apt install -y vdpau-driver-all
sudo apt install -y vim-common
sudo apt install -y vim-tiny
sudo apt install -y vlc-bin
sudo apt install -y vlc-data
sudo apt install -y vlc-l10n
sudo apt install -y vlc-plugin-access-extra
sudo apt install -y vlc-plugin-base
sudo apt install -y vlc-plugin-notify
sudo apt install -y vlc-plugin-qt
sudo apt install -y vlc-plugin-samba
sudo apt install -y vlc-plugin-skins2
sudo apt install -y vlc-plugin-video-output
sudo apt install -y vlc-plugin-video-splitter
sudo apt install -y vlc-plugin-visualization
sudo apt install -y vlc
sudo apt install -y w3m
sudo apt install -y wamerican
sudo apt install -y wbritish
sudo apt install -y webp-pixbuf-loader
sudo apt install -y websocketd
sudo apt install -y wget2
sudo apt install -y wget
sudo apt install -y whiptail
sudo apt install -y whois
sudo apt install -y whoopsie-preferences
sudo apt install -y whoopsie
sudo apt install -y wireless-regdb
sudo apt install -y wireless-tools
sudo apt install -y wireplumber
sudo apt install -y wireshark-common
sudo apt install -y wireshark-qt
sudo apt install -y wireshark
sudo apt install -y wkhtmltopdf
sudo apt install -y wmdocker
sudo apt install -y wordpress-theme-twentytwentytwo
sudo apt install -y wpasupplicant
sudo apt install -y x11-common
sudo apt install -y x11-utils
sudo apt install -y x11-xkb-utils
sudo apt install -y x11-xserver-utils
sudo apt install -y xauth
sudo apt install -y xbrlapi
sudo apt install -y xcursor-themes
sudo apt install -y xdg-dbus-proxy
sudo apt install -y xdg-desktop-portal-gnome
sudo apt install -y xdg-desktop-portal-gtk
sudo apt install -y xdg-desktop-portal
sudo apt install -y xdg-user-dirs-gtk
sudo apt install -y xdg-user-dirs
sudo apt install -y xdg-utils
sudo apt install -y xdotool
sudo apt install -y xfonts-base
sudo apt install -y xfonts-encodings
sudo apt install -y xfonts-utils
sudo apt install -y xkb-data
sudo apt install -y xml-core
sudo apt install -y xorg-docs-core
sudo apt install -y xorriso
sudo apt install -y xserver-common
sudo apt install -y xserver-xephyr
sudo apt install -y xserver-xorg-legacy
sudo apt install -y xvfb
sudo apt install -y xwayland
sudo apt install -y xxd
sudo apt install -y xz-utils
sudo apt install -y yaru-theme-gnome-shell
sudo apt install -y yaru-theme-gtk
sudo apt install -y yaru-theme-icon
sudo apt install -y yaru-theme-sound
sudo apt install -y yelp-xsl
sudo apt install -y yelp
sudo apt install -y zenity-common
sudo apt install -y zenity
sudo apt install -y zip
sudo apt install -y zlib1g-dev
sudo apt install -y zlib1g
sudo apt install -y zstd
